Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2018-06, with the labels that each got.

#2086 README: petites améliorations
  README.md
Labels: tech

#2088 Crée l'utilisateur initial dans les seeds
  README.md
  db/seeds.rb
Labels: tech

#2093 tasks: silence output of tasks during tests
  lib/tasks/2017_07_26_clean_birthdate_on_individual.rake
  lib/tasks/2017_10_18_regenerate_attestation.rake
  lib/tasks/2017_10_30_copy_commentaire_piece_justificative_to_file.rake
  lib/tasks/2017_12_05_initialize_timestamps_for_entreprises.rake
  lib/tasks/2017_12_20_delete_old_administration.rake
  lib/tasks/2018_01_18_clean_datetime_in_champs.rake
  lib/tasks/2018_03_06_clean_html_textareas.rake
  lib/tasks/2018_03_29_remove_code_tags_from_mail_templates.rake
  lib/tasks/2018_04_04_fetch_etablissement_with_no_entreprise.rake
  lib/tasks/2018_06_05_resend_attestations.rake
  lib/tasks/2018_06_05_send_new_attestations.rake
  lib/tasks/2018_06_06_users_for_admins_and_gestionnaires.rake
  lib/tasks/task_helper.rb
  spec/spec_helper.rb
Labels: tech

#2087 Ajoute les fichiers de configuration par défaut à `/config`
  README.md
  config/france_connect.example.yml
  config/github_secrets.example.yml
Labels: tech

#2108 Pimp checkboxes
  app/assets/stylesheets/new_design/forms.scss
  app/helpers/champ_helper.rb
  app/views/shared/dossiers/editable_champs/_checkbox.html.haml
  app/views/shared/dossiers/editable_champs/_editable_champ.html.haml
Labels: admin, usager

#2152 Show siege social siret in accompagnateur view
  app/views/new_gestionnaire/dossiers/_identite_entreprise.html.haml
Labels: bug
