Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2018-10, with the labels that each got.

#2825 spec: move `/spec/lib/rake` to `/spec/lib/tasks`
  spec/lib/tasks/2018_03_06_clean_html_textareas_spec.rb
  spec/lib/tasks/2018_03_29_remove_code_tags_from_mail_templates_spec.rb
  spec/lib/tasks/2018_05_14_add_annotation_privee_to_procedure_spec.rb
  spec/lib/tasks/2018_07_31_nutriscore_spec.rb
Labels: cleaning

#2802 Restore deleted dossiers
  app/mailers/dossier_mailer.rb
  app/views/dossier_mailer/notify_undelete_to_user.html.haml
  app/views/dossier_mailer/notify_unmigrated_to_user.html.haml
  lib/tasks/2018_07_31_nutriscore.rake
  lib/tasks/deployment/20181009130216_restore_deleted_dossiers.rake
  lib/tasks/dossier_procedure_migrator.rb
Labels: bug

#2875 Modification du texte dans le header admin
  app/views/layouts/_navbar.html.haml
Labels: admin

#2879 Modification du titre contact dans le menu instructeur .
  app/views/layouts/_new_header.haml
  spec/views/layouts/_new_header_spec.rb
Labels: instructeur, mineur

#2936 [Fix #2697] When file does not exist on openstack do not crash (Fog::Storage::OpenStack::NotFound)
  app/uploaders/base_uploader.rb
Labels: bug
