Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2020-09, with the labels that each got.

#5538 Fix champ order joins sql error
  app/models/champ.rb
Labels: bug

#5540 remove duplicate private champ
  app/models/champ.rb
  spec/models/champ_spec.rb
Labels: bug

#5563 5546 dropdown accessible
  app/assets/stylesheets/new_design/new_header.scss
  app/javascript/new_design/dropdown.js
  app/views/instructeurs/dossiers/_header_actions.html.haml
  app/views/instructeurs/dossiers/_state_button.html.haml
  app/views/instructeurs/procedures/_download_dossiers.html.haml
  app/views/instructeurs/procedures/show.html.haml
  app/views/invites/_dropdown.html.haml
  app/views/layouts/_account_dropdown.haml
  app/views/new_administrateur/procedures/_procedures_list.html.haml
  app/views/shared/help/_help_dropdown_dossier.html.haml
  app/views/shared/help/_help_dropdown_instructeur.html.haml
  app/views/shared/help/_help_dropdown_procedure.html.haml
  app/views/users/dossiers/_dossier_actions.html.haml
  app/views/users/dossiers/show/_header.html.haml
Labels: accessibilité

#5569 #5571 - Cleanup flipper gates
  app/graphql/types/base_object.rb
  app/models/dossier_operation_log.rb
  app/views/layouts/_main_container.html.haml
  app/views/layouts/_strike_banner.html.haml
  app/views/layouts/application.html.haml
  config/initializers/flipper.rb
  config/routes.rb
  spec/controllers/api/v2/graphql_controller_spec.rb
  spec/controllers/instructeurs/dossiers_controller_spec.rb
Labels: cleaning

#5590 flipper remove :cached_notifications
  app/models/dossier.rb
  app/models/instructeur.rb
  app/models/procedure_presentation.rb
  spec/controllers/instructeurs/dossiers_controller_spec.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/models/dossier_spec.rb
  spec/models/instructeur_spec.rb
  spec/models/procedure_presentation_spec.rb
Labels: cleaning

#5581 Remove :autosave_dossier_draft
  app/helpers/dossier_helper.rb
  config/initializers/flipper.rb
  spec/features/users/brouillon_spec.rb
  spec/features/users/invite_spec.rb
Labels: cleaning

#5567 add aria disclosure for contact page
  app/assets/stylesheets/new_design/common.scss
  app/javascript/new_design/support.js
  app/lib/helpscout/form_adapter.rb
  app/views/support/index.html.haml
  config/locales/views/support/index.en.yml
  config/locales/views/support/index.fr.yml
Labels: accessibilité

#5609 Fix more geometry problems
  app/models/geo_area.rb
  spec/factories/geo_area.rb
  spec/models/geo_area_spec.rb
Labels: bug

#5614 Length sanitization for worksheet exports
  app/models/champs/repetition_champ.rb
  app/services/procedure_export_service.rb
  spec/services/procedure_export_service_spec.rb
Labels: bug

#5616 Bump rubocop
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/stats_controller.rb
  app/helpers/champ_helper.rb
  app/helpers/dossier_helper.rb
  app/helpers/procedure_helper.rb
  app/mailers/application_mailer.rb
  app/mailers/devise_user_mailer.rb
  app/models/procedure_presentation.rb
  app/services/administrateur_usage_statistics_service.rb
  config.ru
  spec/features/routing/full_scenario_spec.rb
  spec/models/attestation_template_spec.rb
  spec/models/concern/tags_substitution_concern_spec.rb
Labels: cleaning

#5627 smaller font-size for large footers in attestation
  app/views/new_administrateur/attestation_templates/show.pdf.prawn
  spec/controllers/new_administrateur/attestation_templates_controller_spec.rb
Labels: bug
