Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2020-07, with the labels that each got.

#5356 mise à jour de doc pour se passer d'overmind
  Procfile
  README.md
  bin/setup
  bin/update
  config/environments/development.rb
Labels: documentation

#5375 Scope usual_traitement_time to the correct dossiers
  app/models/procedure.rb
  spec/features/users/dossier_details_spec.rb
  spec/models/procedure_spec.rb
Labels: bug

#5415 WHEN IE11 DEPRECATED : added the scroll-padding property for pages with sticky-bottoms
  .scss-lint.yml
  app/assets/stylesheets/new_design/layouts.scss
  app/views/layouts/application.html.haml
  app/views/new_administrateur/attestation_templates/edit.html.haml
  app/views/new_administrateur/procedures/edit.html.haml
  app/views/new_administrateur/procedures/new.html.haml
  app/views/users/dossiers/brouillon.html.haml
Labels: accessibilité

#5430 graphql: possibility to filter dossiers by archived
  app/graphql/schema.graphql
  app/graphql/types/demarche_type.rb
  spec/controllers/api/v2/graphql_controller_spec.rb
Labels: API

#5432 fix footer for mail notifications
  app/views/layouts/mailers/notifications_layout.html.erb
Labels: bug

#5418 #5428 - France connect avant les boutons de login/signup
  app/assets/stylesheets/new_design/france-connect-login.scss
  app/views/commencer/show.html.haml
  app/views/shared/_france_connect_login.html.haml
  app/views/users/registrations/new.html.haml
  app/views/users/sessions/new.html.haml
  config/locales/views/shared/fr.yml
Labels: accessibilité
