Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2021-05, with the labels that each got.

#6169 Corrige une duplication des dossiers dans le tableau d'une procedure
  app/models/procedure_presentation.rb
  app/services/dossier_projection_service.rb
  spec/models/procedure_presentation_spec.rb
  spec/services/dossier_projection_service_spec.rb
Labels: bug

#6086 [#6084] rajoute des contraintes manquantes à la table france_connect_informations
  app/models/france_connect_information.rb
  db/migrate/20210504115445_add_constraints_to_france_connect_informations.rb
  db/schema.rb
  spec/controllers/france_connect/particulier_controller_spec.rb
  spec/factories/france_connect_information.rb
  spec/features/france_connect/france_connect_particulier_spec.rb
  spec/lib/tasks/deployment/20210412093054_fill_missing_date_of_fc_spec.rb
  spec/models/france_connect_information_spec.rb
Labels: bug

#6135 petites améliorations de l'UI de instructeur/procedure/show
  app/assets/stylesheets/dossiers_table.scss
  app/views/instructeurs/procedures/_header_field.html.haml
  app/views/instructeurs/procedures/show.html.haml
  app/views/shared/_tab_item.html.haml
  spec/features/instructeurs/instruction_spec.rb
Labels: design

#6192 corrige une traduction manquante pour l'état d'un dossier dans les exports csv/excel ...
  app/models/dossier.rb
  spec/models/dossier_spec.rb
Labels: bug

#6204 Dossier without user should be valid
  app/models/dossier.rb
  spec/models/user_spec.rb
Labels: bug

#6206 Fix dossier deleted user display
  app/models/dossier.rb
  app/views/instructeurs/dossiers/print.html.haml
  app/views/shared/dossiers/_demande.html.haml
  app/views/shared/dossiers/_user_infos.html.haml
  spec/models/user_spec.rb
Labels: bug

#6210 Corrige un mauvais affichage de champ dans le tableau de bord d'une procédure
  app/services/dossier_projection_service.rb
  spec/services/dossier_projection_service_spec.rb
Labels: bug

#6214 corrige le tableau de bord d'une procédure dans le cas ou un champ addresse est affiché
  app/services/dossier_projection_service.rb
  spec/factories/procedure.rb
  spec/services/dossier_projection_service_spec.rb
Labels: bug

#6217 Fix messagerie scroll to last message
  app/javascript/packs/application.js
Labels: bug

#6220 Fix multi select
  app/javascript/components/ComboMultipleDropdownList.jsx
  package.json
  yarn.lock
Labels: bug

#6209 i18n : selecteur de langue
  app/assets/images/icons/translate-icon.svg
  app/controllers/application_controller.rb
  app/controllers/root_controller.rb
  app/views/layouts/_header.haml
  app/views/layouts/_locale_dropdown.html.haml
  config/routes.rb
Labels: traduction

#6232 Do not crash when properties is nil
  app/models/geo_area.rb
  spec/models/geo_area_spec.rb
Labels: bug

#6242 Fix destoying discarded procedures
  app/models/procedure_revision.rb
  spec/models/procedure_spec.rb
Labels: bug
