Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2021-11, with the labels that each got.

#6600 fix(grope_instructeur): can not destroy groupe_instructeur with discarded dossiers
  app/controllers/new_administrateur/groupe_instructeurs_controller.rb
Labels: bug

#6590 fix(dossiers): wrap dossier discard in a transaction
  app/models/deleted_dossier.rb
  app/models/dossier.rb
  app/models/procedure.rb
  app/services/expired_dossiers_deletion_service.rb
Labels: bug

#6577 fix(revisions): fix repetitions export with revisions
  app/models/champs/repetition_champ.rb
  app/models/dossier.rb
  app/models/procedure.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/repetition_type_de_champ.rb
  app/models/types_de_champ/type_de_champ_base.rb
  app/services/procedure_export_service.rb
  spec/models/dossier_spec.rb
  spec/models/procedure_presentation_and_revisions_spec.rb
  spec/models/procedure_revision_spec.rb
Labels: bug

#6611 fix(avis): destroy avis for discarded en_construction dossiers
  app/models/avis.rb
  app/models/dossier.rb
  spec/models/dossier_spec.rb
Labels: bug

#6629 fix(export): remove wrong columns from repetition spreadsheets
  app/models/type_de_champ.rb
  spec/services/procedure_export_service_spec.rb
Labels: bug

#6637 small fix on profil
  app/views/users/profil/show.html.haml
Labels: bug, role:admin

#6642 Merge des comptes avec des fichiers cachés
  app/models/user.rb
  spec/models/user_spec.rb
Labels: bug

#6635 Corriger l'affichage des traitements d'un dossier
  app/models/dossier.rb
  app/views/instructeurs/dossiers/_decisions_rendues_block.html.haml
  config/locales/views/instructeurs/fr.yml
Labels: bug

#6630 fix(procedure): allow to modify duree_conservation_dossiers_dans_ds after publication
  app/controllers/new_administrateur/procedures_controller.rb
  app/helpers/conservation_de_donnees_helper.rb
  app/models/procedure.rb
  spec/controllers/new_administrateur/procedures_controller_spec.rb
  spec/helpers/conservation_de_donnees_helper_spec.rb
Labels: bug

#6644 fix(profile): prevent crashing on renew token action
  app/controllers/users/profil_controller.rb
  app/views/users/profil/show.html.haml
Labels: bug

#6650 fix(champs): save departement info on champ commune
  app/controllers/instructeurs/dossiers_controller.rb
  app/controllers/users/dossiers_controller.rb
  app/javascript/components/ComboCommunesSearch.jsx
  app/javascript/components/ComboSearch.jsx
  app/models/champs/commune_champ.rb
  app/views/shared/dossiers/editable_champs/_communes.html.haml
Labels: bug

#6663 Suppression du code obsolète pour l'auto-validation du chemin des démarches
  app/models/procedure.rb
  app/views/new_administrateur/procedures/_publication_form.html.haml
Labels: cleaning, tech

#6667 Simplification des messages d’erreur en cas de fichier trop volumineux
  Gemfile.lock
  app/models/attestation_template.rb
  app/models/avis.rb
  app/models/champs/piece_justificative_champ.rb
  app/models/champs/titre_identite_champ.rb
  app/models/commentaire.rb
  app/models/concerns/file_validation_concern.rb
  app/models/procedure.rb
  config/i18n-tasks.yml
  config/locales/active_storage_validations.en.yml
  config/locales/active_storage_validations.fr.yml
Labels: tech

#6664 Invalide le cache d'associations d'une nouvelle révision
  app/models/procedure.rb
  spec/models/procedure_spec.rb
Labels: tech

#6669 Fix add depose_at to dossiers
  app/models/dossier.rb
  db/migrate/20211124111429_add_depose_at_to_dossiers.rb
  db/schema.rb
  lib/tasks/deployment/20211124112843_add_depose_at_to_dossiers.rake
  spec/models/dossier_spec.rb
Labels: bug

#6677 fix(commune): do not display foreign departement when selecting commune
  app/javascript/components/ComboCommunesSearch.jsx
  app/javascript/components/ComboDepartementsSearch.jsx
Labels: bug

#6692 Dans le manager, redirige correctement sur après avoir mergé des utilisateurs
  app/controllers/manager/users_controller.rb
  spec/controllers/manager/users_controller_spec.rb
Labels: bug

#6693 ETQ Instructeur, je veux voir les documents que j'ai joins à une demande d'avis
  app/views/instructeurs/shared/avis/_list.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/views/instructeur/shared/avis/list.html.haml_spec.rb
Labels: bug
