Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2021-04, with the labels that each got.

#6054 Met à jour le pied de page
  app/assets/stylesheets/common.scss
  app/views/root/_footer.html.haml
  app/views/users/_general_footer_row.html.haml
Labels: accessibilité

#6063 Prevent crash in preview where there is no siblings
  app/models/champ.rb
  app/models/champs/header_section_champ.rb
Labels: bug

#6077 Ensure address to_s never returns nil
  app/models/champs/address_champ.rb
Labels: bug

#6079 Optimize a bit of instructeur show
  app/controllers/instructeurs/procedures_controller.rb
  app/models/dossier.rb
  app/models/instructeur.rb
  app/models/procedure.rb
  app/views/instructeurs/procedures/show.html.haml
  spec/models/dossier_spec.rb
  spec/models/instructeur_spec.rb
  spec/models/procedure_spec.rb
Labels: performances

#6082 n'utilise plus flipper pour passer outre le login par jeton (1er partie)
  app/models/instructeur.rb
  db/migrate/20210409130604_add_bypass_email_login_token_column_to_instructeur.rb
  db/schema.rb
  lib/tasks/deployment/20210409131949_populate_bypass_email_login.rake
Labels: performances

#6085 [#6084] rempli des dates manquantes dans france_connect_informations
  app/models/france_connect_information.rb
  db/migrate/20210412092710_add_data_column_to_france_connect_informations.rb
  db/schema.rb
  lib/tasks/deployment/20210412093054_fill_missing_date_of_fc.rake
  spec/lib/tasks/deployment/20210412093054_fill_missing_date_of_fc_spec.rb
Labels: bug

#6083 ne demande pas un avis si le dossier a été supprimé
  app/mailers/avis_mailer.rb
  spec/mailers/avis_mailer_spec.rb
Labels: bug

#6091 Fix discarded destruction
  app/models/dossier.rb
  app/models/procedure_revision.rb
  spec/models/dossier_spec.rb
  spec/models/procedure_spec.rb
Labels: bug

#6103 Fix api docs URL
  config/initializers/urls.rb
Labels: bug

#6117 Improuve commune autocomplete results
  app/javascript/components/shared/queryClient.js
Labels: bug

#6134 Améliore la performance de instructeur/dossier/show en évitant un n+1 sur les types de champs
  app/controllers/instructeurs/dossiers_controller.rb
Labels: performances

#6131 ameloration des perfs instructeur show procedure
  app/controllers/instructeurs/procedures_controller.rb
  app/models/expert.rb
  app/models/export.rb
  app/models/instructeur.rb
  app/services/dossier_projection_service.rb
  app/views/instructeurs/dossiers/_header_actions.html.haml
  app/views/instructeurs/procedures/_dossier_actions.html.haml
  app/views/instructeurs/procedures/_download_dossiers.html.haml
  app/views/instructeurs/procedures/_header_field.html.haml
  app/views/instructeurs/procedures/download_export.js.erb
  app/views/instructeurs/procedures/show.html.haml
  app/views/instructeurs/recherche/index.html.haml
  app/views/layouts/_account_dropdown.haml
  app/views/layouts/_header.haml
  app/views/layouts/_search_dossiers_form.html.haml
  spec/factories/export.rb
  spec/models/export_spec.rb
  spec/models/instructeur_spec.rb
  spec/services/dossier_projection_service_spec.rb
  spec/services/notification_service_spec.rb
  spec/views/instructeur/procedures/_download_dossiers.html.haml_spec.rb
Labels: performances
