Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2021-07, with the labels that each got.

#6323 Prevent crashes in combo boxes
  app/javascript/components/shared/hooks.js
Labels: bug

#6328 Fix cadastres layer
  app/javascript/components/shared/mapbox/MapStyleControl.jsx
Labels: bug

#6331 Trigger onStyleChange when leyers are toggled
  app/javascript/components/shared/mapbox/MapStyleControl.jsx
Labels: bug

#6334 views: fix checkbox wrongly selected in multiple_drop_down_list
  app/views/shared/dossiers/editable_champs/_multiple_drop_down_list.html.haml
  spec/views/shared/dossiers/_edit.html.haml_spec.rb
Labels: a-communiquer

#6349 Get more results from communes API and use local matcher
  app/javascript/components/ComboCommunesSearch.jsx
  app/javascript/components/shared/queryClient.js
Labels: bug

#6112 i18n: traduction dossiers/edition
  app/controllers/users/dossiers_controller.rb
  app/helpers/commentaire_helper.rb
  app/helpers/procedure_helper.rb
  app/views/commencer/show.html.haml
  app/views/invites/_dropdown.html.haml
  app/views/invites/_form.html.haml
  app/views/layouts/commencer/_no_procedure.html.haml
  app/views/shared/dossiers/_demande.html.haml
  app/views/shared/dossiers/_edit.html.haml
  app/views/shared/dossiers/messages/_form.html.haml
  app/views/shared/dossiers/messages/_message.html.haml
  app/views/shared/dossiers/messages/_message_issuer.html.haml
  app/views/users/dossiers/_autosave.html.haml
  app/views/users/dossiers/_dossier_actions.html.haml
  app/views/users/dossiers/_dossiers_list.html.haml
  app/views/users/dossiers/demande.html.haml
  app/views/users/dossiers/identite.html.haml
  app/views/users/dossiers/index.html.haml
  app/views/users/dossiers/merci.html.haml
  app/views/users/dossiers/messagerie.html.haml
  app/views/users/dossiers/show/_header.html.haml
  app/views/users/dossiers/show/_latest_message.html.haml
  app/views/users/dossiers/show/_status_overview.html.haml
  app/views/users/sessions/new.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/models/individual/en.yml
  config/locales/models/individual/fr.yml
Labels: traduction

#6357 Fix false positive unspecified tags messages
  app/models/attestation_template.rb
  app/models/champ.rb
  app/models/champs/carte_champ.rb
  app/models/champs/multiple_drop_down_list_champ.rb
  app/models/champs/repetition_champ.rb
  spec/factories/champ.rb
  spec/models/champ_shared_example.rb
  spec/models/dossier_spec.rb
Labels: bug

#6369 fix shared locales namespace
  config/locales/fr.yml
Labels: bug
