Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2022-09, with the labels that each got.

#7706 fix(dossier): fix user form component migration errors
  app/components/editable_champ/linked_drop_down_list_component/linked_drop_down_list_component.html.haml
  app/components/editable_champ/siret_component/siret_component.html.haml
Labels: bug

#7716 fix(css): rename css file to fix legacy browsers
  app/javascript/entrypoints/main.css
  app/views/layouts/application.html.haml
Labels: bug

#7746 fix(conditionnal): corrige les conditions sur les listes de nombre
  app/components/types_de_champ_editor/conditions_component.rb
  app/models/condition_form.rb
  spec/controllers/administrateurs/conditions_controller_spec.rb
  spec/models/condition_form_spec.rb
Labels: bug, conditional

#7772 feat(api_entreprise): n'affiche que le siret si mode dégradé
  app/views/shared/dossiers/_identite_entreprise.html.haml
Labels: bug

#7785 fix-ux(issue#7774) : indicateur menu email navbar
  app/assets/stylesheets/buttons.scss
  app/views/layouts/_account_dropdown.haml
  spec/views/layouts/_header_spec.rb
Labels: UX

#7820 fix(linked_drop_down): corrige l'enregistrement des dropdown liés dans des blocs répétables
  app/javascript/controllers/autosave_controller.ts
Labels: bug, role:usager
