Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2022-08, with the labels that each got.

#7651 fix(autosave): on check condition requests do not send file inputs
  app/javascript/controllers/check_conditions_controller.ts
  app/javascript/shared/utils.test.ts
  app/javascript/shared/utils.ts
Labels: bug

#7662 fix(conditional): mandatory champs inside hidden repetition should not be validated
  app/models/dossier.rb
  spec/models/dossier_spec.rb
Labels: bug, conditional

#7653 feat(champ): can condition on other option
  app/components/types_de_champ_editor/conditions_component.rb
  app/models/champ.rb
  app/models/champs/drop_down_list_champ.rb
  app/models/logic.rb
  app/models/logic/champ_value.rb
  app/models/procedure_revision.rb
  app/models/type_de_champ.rb
  spec/factories/champ.rb
  spec/models/logic/champ_value_spec.rb
Labels: conditional

#7669 fix(conditionnel): corrige les champs obligatoires mais cachés
  app/models/champ.rb
  app/models/champs/piece_justificative_champ.rb
  app/models/champs/siret_champ.rb
  app/models/champs/titre_identite_champ.rb
  app/views/shared/dossiers/editable_champs/_champ_label_content.html.haml
  app/views/shared/dossiers/editable_champs/_linked_drop_down_list.html.haml
  spec/system/users/brouillon_spec.rb
Labels: conditional

#7674 fix(editeur_de_champ): permet d'ajouter à nouveau un template au pjs
  app/controllers/administrateurs/types_de_champ_controller.rb
  app/helpers/champ_helper.rb
  app/javascript/controllers/type_de_champ_editor_controller.ts
  config/routes.rb
  spec/system/administrateurs/types_de_champ_spec.rb
Labels: bug
