Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2022-01, with the labels that each got.

#6791 fix(react): remove register component cache
  app/javascript/shared/register-react-components.jsx
Labels: bug

#6785 fix(a11y): add aria to tabs
  app/views/administrateurs/procedures/apercu.html.haml
  app/views/administrateurs/procedures/index.html.haml
  app/views/experts/avis/_header.html.haml
  app/views/experts/avis/procedure.html.haml
  app/views/instructeurs/avis/_header.html.haml
  app/views/instructeurs/avis/procedure.html.haml
  app/views/instructeurs/dossiers/_header.html.haml
  app/views/instructeurs/procedures/_tabs.html.haml
  app/views/root/patron.html.haml
  app/views/shared/_tab_item.html.haml
  app/views/users/dossiers/index.html.haml
  app/views/users/dossiers/show/_header.html.haml
  spec/views/users/dossiers/index.html.haml_spec.rb
  spec/views/users/dossiers/show/_header.html.haml_spec.rb
Labels: accessibilité

#6801 Correction de Administrateurs::ProcedureAdministrateursController#destroy
  app/controllers/administrateurs/procedure_administrateurs_controller.rb
  spec/controllers/administrateurs/procedure_administrateurs_controller_spec.rb
Labels: bug, tech

#6809 Fix multiselect menu
  app/assets/stylesheets/forms.scss
  app/javascript/components/ComboMultiple.jsx
Labels: bug

#6814 test(system): simplify select menu selector
  app/javascript/components/ComboMultiple.jsx
  app/javascript/components/ComboSearch.jsx
  spec/support/system_helpers.rb
  spec/system/instructeurs/instruction_spec.rb
  spec/system/instructeurs/procedure_filters_spec.rb
Labels: bug

#6813 fix(archives): only export dossiers in archive groupe_instructeurs
  app/models/dossier.rb
  app/models/export.rb
  app/services/procedure_archive_service.rb
  spec/services/procedure_archive_service_spec.rb
Labels: bug

#6826 fix(dossier): do not send notification on expiration when dossier is already deleted
  app/services/expired_dossiers_deletion_service.rb
  spec/services/expired_dossiers_deletion_service_spec.rb
Labels: bug
