Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2022-11, with the labels that each got.

#7988 fix(procedure): fix procedure cards grid view
  app/components/procedure/card/administrateurs_component/administrateurs_component.html.haml
  app/components/procedure/card/annotations_component/annotations_component.html.haml
  app/components/procedure/card/api_entreprise_component/api_entreprise_component.html.haml
  app/components/procedure/card/api_particulier_component/api_particulier_component.html.haml
  app/components/procedure/card/attestation_component/attestation_component.html.haml
  app/components/procedure/card/champs_component/champs_component.html.haml
  app/components/procedure/card/dossier_submitted_message_component/dossier_submitted_message_component.html.haml
  app/components/procedure/card/emails_component/emails_component.html.haml
  app/components/procedure/card/experts_component/experts_component.html.haml
  app/components/procedure/card/instructeurs_component/instructeurs_component.html.haml
  app/components/procedure/card/modifications_component/modifications_component.html.haml
  app/components/procedure/card/mon_avis_component/mon_avis_component.html.haml
  app/components/procedure/card/presentation_component/presentation_component.html.haml
  app/components/procedure/card/service_component/service_component.html.haml
  app/components/procedure/card/zones_component/zones_component.html.haml
  app/views/administrateurs/procedures/show.html.haml
Labels: bug

#8013 fix(merge): transfere les procédures cachées
  app/models/administrateur.rb
  spec/models/administrateur_spec.rb
Labels: bug, role:superadmin

#8014 Feat(FranceConnect): liste les comptes FC liées et permet de les délier
  app/controllers/users/profil_controller.rb
  app/views/users/profil/show.html.haml
  config/locales/views/users/profil/en.yml
  config/locales/views/users/profil/fr.yml
  config/routes.rb
  spec/controllers/users/profil_controller_spec.rb
Labels: role:usager

#8044 fix(turbo-stream): read delay on turbo-stream element
  app/controllers/administrateurs/exports_controller.rb
  app/controllers/instructeurs/procedures_controller.rb
  app/javascript/shared/turbo-actions.ts
  app/models/export.rb
  config/brakeman.ignore
Labels: bug

#8080 feat(a11y): add dsfr skiplinks
  app/javascript/entrypoints/main.css
  app/views/layouts/_skiplinks.html.haml
  app/views/layouts/application.html.haml
Labels: accessibilité

#8131 fix(stats): exported file should be csv
  app/controllers/stats_controller.rb
Labels: bug

#8127 fix(graphql): fix playground when admin has no procedures or dossiers
  app/controllers/graphql_controller.rb
Labels: bug

#8102 fix: escape characters when showing page title
  app/views/layouts/application.html.haml
  spec/system/users/dossier_creation_spec.rb
Labels: bug

#8141 fix(graphql): check if tokens are revoked
  app/controllers/api/v2/base_controller.rb
  spec/controllers/api/v2/graphql_controller_spec.rb
Labels: bug

#8155 fix(dossier): excluded deleted dossiers from demarche overview
  app/models/procedure_overview.rb
  spec/models/procedure_overview_spec.rb
Labels: bug
