Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2022-10, with the labels that each got.

#7833 fix(instructeur dashboard): permets de filtrer les dossiers sur plusieurs états
  app/models/procedure_presentation.rb
  spec/models/procedure_presentation_spec.rb
Labels: bug, role:instructeur

#7836 fix(web_graphql): corrige l'authorisation d'acces au bac à sable graphql
  app/controllers/api/v2/base_controller.rb
Labels: bug, role:admin

#7909 fix(export): met une valeur null aux champs cachés lors des exports
  app/models/dossier.rb
  spec/models/dossier_spec.rb
Labels: bug, conditional

#7918 fix(routage): fill dossier groupe instructeur in some edge cases
  app/controllers/users/dossiers_controller.rb
Labels: bug

#7928 fix(export): corrige un bug apparaissant avec des revisions et du conditionnel
  app/models/dossier.rb
  spec/models/dossier_spec.rb
Labels: bug

#7933 fix(dossier): nullify instructeur and expert id on messages when they are deleted
  app/models/commentaire.rb
  app/models/expert.rb
  app/models/instructeur.rb
  lib/tasks/deployment/20221019094123_nullify_commentaire_deleted_instructeurs.rake
Labels: bug

#7935 fix(admin_merge): résout un pb lorsque les 2 admins ont un service avec le mm nom
  app/models/administrateur.rb
  spec/models/administrateur_spec.rb
Labels: bug

#7941 fix(message): add instructeurs foreign key
  db/migrate/20221020094031_add_foreign_key_to_commentaires_instructeur_id.rb
  db/schema.rb
Labels: bug

#7945 fix(dolist): réduit le nombre de 'Message-Name' possible chez dolist
  app/mailers/application_mailer.rb
  config/initializers/dolist.rb
Labels: bug

#7950 fix(dossier): a tag can be preceded by a -
  app/models/concerns/tags_substitution_concern.rb
  app/models/types_de_champ/type_de_champ_base.rb
  spec/models/concern/tags_substitution_concern_spec.rb
Labels: bug

#7956 fix(editeur): supprime un 'end' surnuméraire
  app/views/administrateurs/conditions/_update.turbo_stream.haml
Labels: bug, role:admin

#7960 fix(editeur de champ): corrige la perte de focus lors de l'édition de champ
  app/javascript/controllers/type_de_champ_editor_controller.ts
  app/javascript/shared/turbo-actions.ts
  app/views/administrateurs/types_de_champ/_insert.turbo_stream.haml
Labels: bug, role:admin

#7964 fix(migration): ignore strong migration pour la petite table procédures
  db/migrate/20221006074425_add_tags_to_procedures.rb
Labels: bug

#7965 fix(merge): s'assure que les transfert de service lors des merges d'administrateur fonctionnent
  app/models/administrateur.rb
Labels: bug

#7977 fix(graphql): do not load brouillon or deleted linked dossier
  app/graphql/loaders/dossier.rb
  app/graphql/types/champs/dossier_link_champ_type.rb
  spec/graphql/dossier_spec.rb
Labels: bug

#7979 fix(graphql): properly handle variables json parse errors
  app/controllers/api/v2/graphql_controller.rb
  spec/controllers/api/v2/graphql_controller_spec.rb
Labels: bug
