Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2023-12, with the labels that each got.

#9762 fix(email_template): less magic - less bugs !
  app/controllers/administrateurs/mail_templates_controller.rb
  app/dashboards/procedure_dashboard.rb
  app/mailers/notification_mailer.rb
  app/models/dossier.rb
  app/models/procedure.rb
  app/services/mail_template_presenter_service.rb
  spec/controllers/administrateurs/mail_templates_controller_spec.rb
  spec/mailers/notification_mailer_spec.rb
  spec/models/dossier_spec.rb
  spec/models/procedure_spec.rb
Labels: bug

#9799 ETQ instructeur, lorsque je motive une décision, la motivation est désormais bien formatée
  app/models/concerns/tags_substitution_concern.rb
  spec/models/concern/tags_substitution_concern_spec.rb
Labels: a-communiquer

#9831 ETQ usager ou instructeur, la motivation est bien formatée sur la page du dossier
  app/views/shared/dossiers/_infos_generales.html.haml
  app/views/users/dossiers/show/_status_overview.html.haml
Labels: a-communiquer

#9821 ETQ instructeur je ne peux pas passer en instruction un dossier en attente de correction
  app/javascript/entrypoints/main.css
  app/jobs/process_stalled_declarative_dossier_job.rb
  app/models/dossier.rb
  app/views/instructeurs/dossiers/_header_actions.html.haml
  app/views/instructeurs/procedures/_dossier_actions.html.haml
  app/views/instructeurs/procedures/show.html.haml
  app/views/recherche/index.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/jobs/process_stalled_declarative_dossier_job_spec.rb
  spec/models/dossier_spec.rb
  spec/views/instructeur/dossiers/show.html.haml_spec.rb
Labels: a-communiquer, Fonds Vert

#9840 ETQ superadmin je peux mettre à jour le brouillon d'une révision à partir d'un CSV
  app/tasks/maintenance/delete_draft_revision_type_de_champs_task.rb
  app/tasks/maintenance/update_draft_revision_type_de_champs_task.rb
  spec/tasks/maintenance/delete_draft_revision_type_de_champs_task_spec.rb
  spec/tasks/maintenance/update_draft_revision_type_de_champs_task_spec.rb
Labels: Fonds Vert

#9881 Correction : une condition / règle de routage du type "un département est dans une région" est valide
  app/models/champs/departement_champ.rb
  spec/models/logic/champ_value_spec.rb
Labels: bug

#9880 API: stocke les ips utilisées pour accéder à l'API
  app/controllers/api/v2/base_controller.rb
  app/controllers/api_controller.rb
  app/models/api_token.rb
  db/migrate/20231221142727_add_last_used_ips_column_to_api_token.rb
  db/schema.rb
  spec/models/api_token_spec.rb
Labels: API
