Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2023-02, with the labels that each got.

#8535 fix(dossier): fix adding repetition in a new revision
  app/jobs/migrations/backfill_dossier_repetition_job.rb
  app/models/concerns/dossier_rebase_concern.rb
  lib/tasks/deployment/20230201090534_backfill_dossiers_repetitions.rake
  spec/models/dossier_rebase_concern_spec.rb
Labels: bug

#8545 fix(task): improuve after party backfill_dossiers_repetitions
  app/jobs/migrations/backfill_dossier_repetition_job.rb
  lib/tasks/deployment/20230201090534_backfill_dossiers_repetitions.rake
  lib/tasks/deployment/20230201090535_backfill_dossiers_repetitions.rake
Labels: bug

#8546 fix(dossier): do not try to rebase if procedure is not published
  app/models/concerns/dossier_rebase_concern.rb
  spec/models/concern/dossier_rebase_concern_spec.rb
Labels: bug

#8505 migrate(champs): normalize departements
  lib/tasks/deployment/20221221153640_normalize_checkbox_values.rake
  lib/tasks/deployment/20221221155508_normalize_yes_no_values.rake
  lib/tasks/deployment/20230126102100_normalize_departements.rake
  spec/lib/tasks/deployment/20230126102100_normalize_departements_spec.rake
Labels: API

#8561 fix(dossiers_transfers): users can reject dossiers_transfers
  app/controllers/users/transfers_controller.rb
  spec/controllers/users/transfers_controller_spec.rb
Labels: bug

#8587 fix(dossier): prevent crash in rebase
  app/models/procedure_revision.rb
  spec/models/concern/dossier_rebase_concern_spec.rb
  spec/models/procedure_revision_spec.rb
Labels: bug

#8585 fix(dossier/démarche en test): peut détruire des dossiers référencés dans des opérations de masse
  app/controllers/administrateurs/administrateur_controller.rb
  app/models/dossier.rb
Labels: bug

#8594 fix(dossier): prevent crash when updating champs in rebase
  app/models/concerns/dossier_rebase_concern.rb
Labels: bug

#8601 fix(geo_area): geo_area.geometry must be valid JSON, not nil
  lib/tasks/deployment/20230208154144_fix_geo_area_without_geometry.rake
Labels: bug

#8603 fix(export/job): race condition when export was already generated
  app/jobs/export_job.rb
  app/models/export.rb
Labels: bug

#8607 fix(revision): backfill missing published_at
  lib/tasks/deployment/20230209093144_backfill_revisions_published_at.rake
Labels: bug

#8613 Email: limite le sujet généré à 100 caractères et utilise le sujet par défaut si le modèle est vide
  app/mailers/notification_mailer.rb
  app/models/concerns/mail_template_concern.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/mailers/notification_mailer_spec.rb
Labels: bug

#8472 feat(dossier): prefill departements champ
  app/models/champs/departement_champ.rb
  app/models/prefill_params.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_departement_type_de_champ.rb
  app/models/types_de_champ/prefill_pays_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/api/v1/dossiers_controller_spec.rb
  spec/controllers/api/v2/graphql_controller_spec.rb
  spec/models/champs/departement_champ_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_departement_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_pays_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
Labels: API

#8576 feat(dossier): prefill epci champ
  app/models/champs/epci_champ.rb
  app/models/prefill_description.rb
  app/models/prefill_params.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_epci_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/models/champs/epci_champ_spec.rb
  spec/models/prefill_description_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_epci_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8609 fix(procedures/all): table layout issue
  app/views/administrateurs/procedures/_detail.html.haml
Labels: bug

#8626 feat(groupe instructeur mailer): add emailing to removed instructeurs
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  app/controllers/instructeurs/groupe_instructeurs_controller.rb
  app/graphql/mutations/groupe_instructeur_supprimer_instructeurs.rb
  app/mailers/groupe_instructeur_mailer.rb
  app/views/groupe_instructeur_mailer/notify_group_when_instructeurs_removed.html.haml
  app/views/groupe_instructeur_mailer/notify_removed_instructeur.html.haml
  app/views/groupe_instructeur_mailer/remove_instructeur.html.haml
  app/views/groupe_instructeur_mailer/remove_instructeurs.html.haml
  config/locales/views/administrateurs/groupe_instructeurs/en.yml
  config/locales/views/administrateurs/groupe_instructeurs/fr.yml
  spec/controllers/administrateurs/groupe_instructeurs_controller_spec.rb
  spec/mailers/groupe_instructeur_mailer_spec.rb
  spec/mailers/previews/groupe_instructeur_mailer_preview.rb
Labels: support

#8479 prefill(dossier): prefill multiple drop down list champ
  app/models/champs/multiple_drop_down_list_champ.rb
  app/models/prefill_params.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_multiple_drop_down_list_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/instructeurs/dossiers_controller_spec.rb
  spec/factories/champ.rb
  spec/models/champ_spec.rb
  spec/models/champs/multiple_drop_down_list_champ_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_multiple_drop_down_list_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8636 fix(graphql): fix demarcheUrl
  app/graphql/api/v2/stored_query.rb
  app/graphql/types/demarche_descriptor_type.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
  spec/services/demarches_publiques_export_service_spec.rb
Labels: bug

#8685 feat(dossier): prefill communes champ
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_commune_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  app/services/api_geo_service.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/fixtures/cassettes/api_geo_communes.yml
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_commune_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/services/api_geo_service_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8698 fix(autocomplete): avoid double escape of query params
  app/javascript/components/shared/queryClient.ts
Labels: bug

#8694 fix(filter): fix find type de champ by stable_id
  app/models/procedure_presentation.rb
Labels: bug

#8388 feat(dossier): prefill siret champ
  app/components/editable_champ/siret_component/siret_component.html.haml
  app/controllers/champs/siret_controller.rb
  app/javascript/controllers/turbo_input_controller.tsx
  app/models/champs/siret_champ.rb
  app/models/concerns/siret_champ_etablissement_fetchable_concern.rb
  app/models/type_de_champ.rb
  app/services/api_entreprise_service.rb
  app/views/champs/siret/show.turbo_stream.haml
  app/views/shared/champs/siret/_etablissement.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/champs/siret_controller_spec.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/models/concern/dossier_prefillable_concern_spec.rb
  spec/models/concern/siret_champ_etablissement_fetchable_concern_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/services/api_entreprise_service_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8424 feat(dossier): prefill rna champ
  app/components/editable_champ/rna_component/rna_component.html.haml
  app/controllers/champs/rna_controller.rb
  app/models/champs/rna_champ.rb
  app/models/concerns/rna_champ_association_fetchable_concern.rb
  app/models/type_de_champ.rb
  app/views/champs/rna/show.turbo_stream.haml
  app/views/shared/champs/rna/_association.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/champs/rna_controller_spec.rb
  spec/models/concern/rna_champ_association_fetchable_concern_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8679 feat(dossier): prefill dossier link champ
  app/models/champs/dossier_link_champ.rb
  app/models/prefill_params.rb
  app/models/type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/models/champs/dossier_link_champ_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8704 fix possible values
  app/models/types_de_champ/prefill_commune_type_de_champ.rb
  app/models/types_de_champ/prefill_epci_type_de_champ.rb
  app/views/prefill_type_de_champs/show.html.haml
  spec/models/types_de_champ/prefill_commune_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_epci_type_de_champ_spec.rb
Labels: bug

#8702 fix(combo-address): provide a valid empty response
  app/javascript/components/shared/queryClient.ts
Labels: bug

#8713 fix(graphql): fix etablissement as_degraded_mode?
  app/graphql/types/champs/siret_champ_type.rb
Labels: bug

#8639 refactor(progress): move progress bar markup to haml
  app/components/attachment/progress_bar_component.rb
  app/components/attachment/progress_bar_component/progress_bar_component.en.yml
  app/components/attachment/progress_bar_component/progress_bar_component.fr.yml
  app/components/attachment/progress_bar_component/progress_bar_component.html.haml
  app/javascript/shared/activestorage/progress-bar.ts
  app/views/layouts/application.html.haml
Labels: accessibilité

#8712 fix(annotations-privees): initialisation de la numérotation automatique
  app/views/shared/dossiers/_edit_annotations.html.haml
Labels: bug
