Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2023-03, with the labels that each got.

#8625 feat(dossier): prefill annuaire education champ
  app/jobs/champ_fetch_external_data_job.rb
  app/models/champ.rb
  app/models/champs/annuaire_education_champ.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_annuaire_education_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/fixtures/files/api_education/annuaire_education_empty.json
  spec/jobs/champ_fetch_external_data_job_spec.rb
  spec/lib/api_education/annuaire_education_adapter_spec.rb
  spec/models/champ_spec.rb
  spec/models/champs/annuaire_education_champ_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_annuaire_education_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8677 a11y(combosearch): instructions pour lecteurs d'écran et annonce l'arrivée des résultats
  app/components/editable_champ/address_component.rb
  app/components/editable_champ/address_component/address_component.html.haml
  app/components/editable_champ/annuaire_education_component.rb
  app/components/editable_champ/annuaire_education_component/annuaire_education_component.html.haml
  app/components/editable_champ/carte_component.rb
  app/components/editable_champ/carte_component/carte_component.html.haml
  app/components/editable_champ/combo_search_component.rb
  app/components/editable_champ/combo_search_component/combo_search_component.html.haml
  app/components/editable_champ/communes_component.rb
  app/components/editable_champ/communes_component/communes_component.html.haml
  app/javascript/components/ComboSearch.tsx
  app/javascript/components/MapEditor/components/AddressInput.tsx
  app/javascript/components/MapEditor/index.tsx
  config/i18n-tasks.yml
  config/locales/en.yml
  config/locales/fr.yml
Labels: accessibilité

#8707 feat(dossier): prefill address champ
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_address_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_address_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: API

#8724 fix(graphql): fix etablissement in degraded mode
  app/graphql/types/champs/siret_champ_type.rb
  spec/graphql/dossier_spec.rb
Labels: bug

#8722 feat(groupe instructeur): do not notify group when instructeurs removed
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  app/controllers/instructeurs/groupe_instructeurs_controller.rb
  app/graphql/mutations/groupe_instructeur_supprimer_instructeurs.rb
  app/mailers/groupe_instructeur_mailer.rb
  app/views/groupe_instructeur_mailer/notify_group_when_instructeurs_removed.html.haml
  config/locales/views/groupe_instructeur_mailer/notify_group_when_instructeurs_removed/en.yml
  config/locales/views/groupe_instructeur_mailer/notify_group_when_instructeurs_removed/fr.yml
  spec/mailers/groupe_instructeur_mailer_spec.rb
  spec/mailers/previews/groupe_instructeur_mailer_preview.rb
Labels: support

#8725 correctif(admin/procedures#champs): ajoute le formulaire pour supprimer une PJ
  app/views/administrateurs/procedures/annotations.html.haml
  app/views/administrateurs/procedures/champs.html.haml
Labels: bug

#8678 fix(a11y): improve Explication "lire plus" accessibility
  app/components/editable_champ/explication_component/explication_component.html.haml
Labels: accessibilité

#8750 Jobs: rallonge durée max pour les exports, fix des timeouts, isole DossierRebase
  app/jobs/application_job.rb
  app/jobs/archive_creation_job.rb
  app/jobs/cron/purge_old_email_event_job.rb
  app/jobs/dossier_rebase_job.rb
  app/jobs/export_job.rb
  app/models/archive.rb
  app/models/dossier.rb
  app/services/serializer_service.rb
  config/initializers/delayed_job.rb
Labels: bug

#8748 Administrateur: le clone d'une démarche ne copie pas le cache du nombre de dossiers
  app/models/procedure.rb
  spec/models/procedure_spec.rb
Labels: bug

#8749 Administrateur: ne supprime pas les tags quand on n'interagit pas avec la liste de sélection
  app/views/administrateurs/procedures/_informations.html.haml
  spec/system/administrateurs/procedure_update_spec.rb
Labels: bug

#8753 Fix(dossier): ne numérote pas automatiquement les titres de section dans les répétitions
  app/models/concerns/dossier_sections_concern.rb
  spec/models/concern/dossier_sections_concern_spec.rb
Labels: bug

#8756 fix(job): ExpiredDossiersDeletionJob détruit en batch les dossiers en brouillon expirés
  app/services/expired_dossiers_deletion_service.rb
Labels: bug

#8765 Fix dossier/pdf: remplace les feature collections du champ carte par les libellés de sélection utilisateur
  app/views/dossiers/show.pdf.prawn
Labels: bug

#8769 Fix: crash d'annotations privées à cause d'une incohérence avec leur type de champ
  app/components/procedure/revision_changes_component/revision_changes_component.fr.yml
  app/controllers/application_controller.rb
  app/controllers/instructeurs/dossiers_controller.rb
  app/controllers/users/dossiers_controller.rb
  lib/tasks/deployment/20230316125244_fix_champ_type_mismatch.rake
  lib/tasks/task_helper.rb
Labels: bug

#8796 fix(dossier): fix rebasing submitted dossiers private champs type changes
  app/models/concerns/dossier_rebase_concern.rb
  spec/models/concern/dossier_rebase_concern_spec.rb
Labels: bug

#8799 fix(dossier): champ explication collapsible explanation should be formatted
  app/components/editable_champ/explication_component/explication_component.html.haml
Labels: bug

#8816 Fix avis: n'affiche pas le form de réponse à la question s'il n'y a pas de question
  app/models/avis.rb
  app/views/experts/avis/instruction.html.haml
  app/views/shared/avis/_form.html.haml
  spec/models/avis_spec.rb
  spec/views/experts/avis/instruction.html.haml_spec.rb
Labels: bug

#8826 Fix champ explication: cache le texte qui doit être caché
  app/components/editable_champ/explication_component/explication_component.html.haml
  spec/components/editable_champ/explication_component/explication_component_spec.rb
Labels: bug

#8828 Fix (manager): ne trie pas par created_at pour ne pas casser la prod
  app/controllers/manager/application_controller.rb
  app/dashboards/administrateur_dashboard.rb
  app/dashboards/instructeur_dashboard.rb
  app/dashboards/user_dashboard.rb
Labels: bug
