Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2023-05, with the labels that each got.

#8998 ETQ Instructeur et Usager: corrige le téléchargement des attestations
  app/controllers/instructeurs/dossiers_controller.rb
  app/controllers/users/dossiers_controller.rb
Labels: bug

#8989 ETQ Instructeur, je ne veux pas d'erreurs quand les filtres ne sont pas trouvés
  app/controllers/instructeurs/procedures_controller.rb
Labels: bug

#8999 ETQ instructeur, ne plante pas un export s'il contient des PJ avec des noms de fichiers invalides
  app/lib/download_manager/parallel_download_queue.rb
  spec/lib/download_manager/parallel_download_queue_spec.rb
Labels: bug

#9003 ETQ Instructeur, je ne veux pas voir les dossiers terminés dans l'onglet "suivis"
  app/models/dossier.rb
  spec/models/procedure_presentation_spec.rb
Labels: bug

#9001 ETQ développeur je veux pouvoir utiliser les urls d'attachments en local
  config/environments/development.rb
Labels: tech

#9024 Admin: fix affichage d'un avertissement dans le résumé des changements bloquants d'une nouvelle révision
  app/components/procedure/revision_changes_component/revision_changes_component.html.haml
Labels: bug

#9021 ETQ usager, je modifie et soumets à nouveau mon dossier “en construction"
  app/assets/stylesheets/_colors.scss
  app/assets/stylesheets/landing.scss
  app/assets/stylesheets/status_overview.scss
  app/assets/stylesheets/sub_header.scss
  app/components/dossiers/autosave_footer_component/autosave_footer_component.en.yml
  app/components/dossiers/autosave_footer_component/autosave_footer_component.fr.yml
  app/components/dossiers/autosave_footer_component/autosave_footer_component.html.haml
  app/components/dossiers/edit_footer_component.rb
  app/components/dossiers/edit_footer_component/edit_footer_component.en.yml
  app/components/dossiers/edit_footer_component/edit_footer_component.fr.yml
  app/components/dossiers/edit_footer_component/edit_footer_component.html.haml
  app/components/dossiers/en_construction_not_submitted_component.rb
  app/components/dossiers/en_construction_not_submitted_component/en_construction_not_submitted_component.en.yml
  app/components/dossiers/en_construction_not_submitted_component/en_construction_not_submitted_component.fr.yml
  app/components/dossiers/en_construction_not_submitted_component/en_construction_not_submitted_component.html.haml
  app/components/dsfr/callout_component.rb
  app/components/editable_champ/champ_label_component/champ_label_component.html.haml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.en.yml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.fr.yml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
  app/controllers/concerns/turbo_champs_concern.rb
  app/controllers/users/dossiers_controller.rb
  app/graphql/mutations/dossier_changer_groupe_instructeur.rb
  app/jobs/destroy_record_later_job.rb
  app/jobs/dossier_update_search_terms_job.rb
  app/models/champ.rb
  app/models/concerns/dossier_clone_concern.rb
  app/models/concerns/dossier_searchable_concern.rb
  app/models/dossier.rb
  app/models/routing_engine.rb
  app/views/shared/dossiers/_edit.html.haml
  app/views/users/dossiers/demande.html.haml
  app/views/users/dossiers/modifier_legacy.turbo_stream.haml
  app/views/users/dossiers/show.html.haml
  app/views/users/dossiers/show/_status_overview.html.haml
  app/views/users/dossiers/update.turbo_stream.haml
  config/routes.rb
  db/migrate/20230113165022_add_editing_forks_to_dossiers.rb
  db/schema.rb
  spec/components/dossiers/en_construction_not_submitted_component_spec.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/jobs/dossier_update_search_terms_job_spec.rb
  spec/models/concern/dossier_clone_concern_spec.rb
  spec/models/concern/dossier_searchable_concern_spec.rb
  spec/models/dossier_spec.rb
  spec/models/routing_engine_spec.rb
  spec/system/routing/full_scenario_spec.rb
  spec/system/routing/rules_full_scenario_spec.rb
  spec/system/users/brouillon_spec.rb
  spec/system/users/dossier_shared_examples.rb
  spec/system/users/en_construction_spec.rb
  spec/views/shared/dossiers/_edit.html.haml_spec.rb
  spec/views/users/dossiers/show.html.haml_spec.rb
Labels: role:usager

#9041 fix(dossier): task to fix cloned published revisions
  lib/tasks/deployment/20230512103830_fix_cloned_published_revisions.rake
  spec/lib/tasks/deployment/20230512103830_fix_cloned_revisions_spec.rb
Labels: bug

#9035 Correctif: ETQ usager le champ PJ d'un dossier en construction ne doit pas être marqué "à déposer" sans raison
  app/models/concerns/dossier_clone_concern.rb
  spec/models/concern/dossier_clone_concern_spec.rb
  spec/models/dossier_spec.rb
Labels: bug

#9036 ETQ Usager: correctifs pour les modifications en construction
  app/controllers/users/dossiers_controller.rb
  app/views/champs/piece_justificative/show.turbo_stream.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/users/dossiers_controller_spec.rb
Labels: bug

#9034 ETQ Admin/Usager: améliore les messages du compteur de caractères
  app/components/editable_champ/textarea_component/textarea_component.en.yml
  app/components/editable_champ/textarea_component/textarea_component.fr.yml
  app/components/editable_champ/textarea_component/textarea_component.html.haml
  app/components/types_de_champ_editor/champ_component.rb
  app/components/types_de_champ_editor/champ_component/champ_component.fr.yml
  app/components/types_de_champ_editor/champ_component/champ_component.html.haml
  app/models/champs/textarea_champ.rb
Labels: bug

#9061 fix(revision): backfill missing published_at on published revisions
  lib/tasks/deployment/20230516152457_fix_procedure_revision_publiee_without_published_at.rake
Labels: bug

#9072 ETQ admin: corrige une erreur lorsque je modifie mon dossier en construction d'une démarche en test
  app/models/concerns/dossier_rebase_concern.rb
  spec/models/concern/dossier_rebase_concern_spec.rb
Labels: bug

#9076 ETQ instructeur je peux filtrer les dossiers par avis
  app/controllers/instructeurs/procedures_controller.rb
  app/models/procedure_presentation.rb
  config/locales/models/procedure_presentation/en.yml
  config/locales/models/procedure_presentation/fr.yml
  spec/models/procedure_presentation_spec.rb
Labels: bug

#9032 Usager: plus de détails sur les raisons qui expliquent pourquoi je ne reçois pas l'email "mot de passe perdu"
  app/views/users/passwords/reset_link_sent.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/system/users/managing_password_spec.rb
Labels: role:usager

#9086 ETQ usager je peux modifier un dossier en_construction qui contient des champs en erreur
  app/models/concerns/dossier_clone_concern.rb
  spec/models/concern/dossier_clone_concern_spec.rb
Labels: bug

#9088 ETQ usager invité sur un dossier, je peux ajouter une PJ d'un dossier en construction
  app/policies/champ_policy.rb
  spec/policies/champ_policy_spec.rb
Labels: bug

#9085 ETQ intégrateur d’API, je voudrais voir un message d’erreur si le changement d’état échoue
  app/graphql/mutations/dossier_classer_sans_suite.rb
  app/graphql/mutations/dossier_refuser.rb
  spec/controllers/api/v2/graphql_controller_spec.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
Labels: bug
