Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2023-01, with the labels that each got.

#8233 feat(demarche): create and prefill a dossier with POST request
  app/controllers/api/public/v1/base_controller.rb
  app/controllers/api/public/v1/dossiers_controller.rb
  app/controllers/concerns/procedure_context_concern.rb
  app/controllers/users/commencer_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/helpers/procedure_helper.rb
  app/mailers/devise_user_mailer.rb
  app/models/concerns/dossier_prefillable_concern.rb
  app/models/current_confirmation.rb
  app/models/dossier.rb
  app/models/procedure.rb
  app/models/user.rb
  app/views/commencer/show.html.haml
  app/views/devise_mailer/confirmation_instructions.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  db/migrate/20221213084333_add_prefill_fields_to_dossiers.rb
  db/migrate/20221213084442_add_prefill_token_index_to_dossiers.rb
  db/schema.rb
  spec/controllers/api/public/v1/dossiers_controller_spec.rb
  spec/controllers/concerns/procedure_context_concern_spec.rb
  spec/controllers/users/commencer_controller_spec.rb
  spec/factories/dossier.rb
  spec/mailers/previews/devise_user_mailer_preview.rb
  spec/models/concern/dossier_prefillable_concern_spec.rb
  spec/models/dossier_spec.rb
  spec/support/public_api_matchers.rb
  spec/support/shared_examples_for_prefilled_dossier.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
  spec/system/users/dossier_prefill_spec.rb
Labels: API

#8298 feat(demarche): describe dossier prefilling with POST
  app/models/prefill_description.rb
  app/views/prefill_descriptions/_prefill_query.html.haml
  app/views/prefill_descriptions/edit.html.haml
  app/views/prefill_descriptions/update.turbo_stream.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  spec/controllers/prefillings_controller_spec.rb
  spec/models/prefill_description_spec.rb
  spec/system/integrateurs/procedure_prefilling_spec.rb
Labels: API

#8366 remove preremplir admin button
  app/views/administrateurs/procedures/show.html.haml
Labels: API

#8370 fix(template): trix will transform double spaces in &nbsp;
  app/models/concerns/tags_substitution_concern.rb
  spec/models/concern/tags_substitution_concern_spec.rb
Labels: bug

#8371 rename file to match controller name
  spec/controllers/prefill_descriptions_controller_spec.rb
Labels: API

#8372 :coffin: remove dead route
  config/routes.rb
Labels: API

#8374 fix(graphql): fix departements with alphanumeric codes
  app/models/champs/departement_champ.rb
  spec/models/champs/departement_champ_spec.rb
Labels: bug

#8381 feat(dossier): prefill boolean champs
  app/models/champs/boolean_champ.rb
  app/models/prefill_params.rb
  app/models/type_de_champ.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
Labels: API

#8382 feat(dossier): add dossier id to prefill response
  app/controllers/api/public/v1/dossiers_controller.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/api/public/v1/dossiers_controller_spec.rb
Labels: API

#8408 fix(dossier): disable buttons when selection is canceled
  app/components/dossiers/batch_operation_component.rb
  app/javascript/controllers/batch_operation_controller.ts
Labels: bug

#8420 fix(procedure): return most recent demarche for a given path
  app/controllers/users/commencer_controller.rb
Labels: bug

#8439 fix(graphql): n+1 on single dossier loading
  app/graphql/types/query_type.rb
Labels: bug

#8443 fix(after_party): DateTimeChamp -> DatetimeChamp
  lib/tasks/deployment/20221221170137_normalize_datetime_values.rake
Labels: bug

#8361 feat(dossier): prefill drop down list champ
  app/controllers/prefill_type_de_champs_controller.rb
  app/models/champs/drop_down_list_champ.rb
  app/models/prefill_description.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_drop_down_list_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  app/views/prefill_descriptions/_types_de_champs.html.haml
  app/views/prefill_type_de_champs/show.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/routes.rb
  spec/controllers/prefill_type_de_champs_controller_spec.rb
  spec/factories/champ.rb
  spec/models/champs/drop_down_list_champ_spec.rb
  spec/models/prefill_description_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_drop_down_list_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/views/prefill_descriptions/_types_de_champs.html.haml_spec.rb
  spec/views/shared/dossiers/_edit.html.haml_spec.rb
Labels: API

#8461 fix(graphql): demarche with pj should return schema
  app/graphql/api/v2/stored_query.rb
  app/graphql/extensions/attachment.rb
  app/graphql/types/champ_descriptor_type.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
Labels: bug

#8464 fix(prefill): don't mark the dossier as prefilled when it's not
  app/models/concerns/dossier_prefillable_concern.rb
  spec/models/concern/dossier_prefillable_concern_spec.rb
Labels: API

#8470 fix(graphql): remove deprecated options from introspection query
  app/graphql/api/v2/context.rb
  app/graphql/api/v2/stored_query.rb
  app/graphql/schema.graphql
  app/graphql/types/base_field.rb
  app/graphql/types/base_interface.rb
  app/graphql/types/base_object.rb
  app/graphql/types/demarche_descriptor_type.rb
  app/graphql/types/query_type.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
Labels: bug

#8436 feat(demarche): prefilling stats
  app/controllers/api/public/v1/base_controller.rb
  app/controllers/api/public/v1/stats_controller.rb
  config/routes.rb
  spec/controllers/api/public/v1/stats_controller_spec.rb
  spec/models/concern/procedure_stats_concern_spec.rb
Labels: API

#8476 Hs/2110477668/2009283
  app/views/dossiers/show.pdf.prawn
Labels: bug

#8478 amelioration(modele_attestation): re-tente a génération de l'attestation dans le cas ou notre objectstorage est en bagotage
  app/views/administrateurs/attestation_templates/show.pdf.prawn
Labels: bug

#8477 fix(prefill): code pays display
  app/models/types_de_champ/prefill_pays_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  app/views/prefill_descriptions/_types_de_champs.html.haml
  spec/models/types_de_champ/prefill_pays_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
Labels: bug, API

#8442 feat(dossier): prefill region champ
  app/models/champs/region_champ.rb
  app/models/prefill_params.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_region_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/controllers/api/v2/graphql_controller_spec.rb
  spec/lib/tasks/deployment/20220705164551_remove_unused_champs_spec.rb
  spec/models/champ_spec.rb
  spec/models/champs/region_champ_spec.rb
  spec/models/dossier_spec.rb
  spec/models/prefill_params_spec.rb
  spec/models/type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_region_type_de_champ_spec.rb
  spec/models/types_de_champ/prefill_type_de_champ_spec.rb
  spec/services/procedure_export_service_spec.rb
Labels: API

#8503 fix(morph): ids should not start with numbers
  app/models/champ.rb
Labels: bug

#8516 fix(dossier): fix clone with data
  app/models/champ.rb
  spec/models/dossier_spec.rb
Labels: bug

#8520 fix(stimulus): "on" handler having target
  app/javascript/controllers/application_controller.ts
Labels: bug

#8514 fix(dossier): set rebased_at only on changed champs
  app/models/concerns/dossier_rebase_concern.rb
  spec/models/dossier_rebase_concern_spec.rb
Labels: bug

#8491 Fix: champ "autre" d'une liste déroulante qui écrasait une option de la liste
  app/assets/stylesheets/forms.scss
  app/components/editable_champ/drop_down_other_input_component/drop_down_other_input_component.html.haml
  app/javascript/controllers/autosave_controller.ts
  app/javascript/controllers/champ_dropdown_controller.ts
  spec/system/users/dropdown_spec.rb
Labels: bug

#8524 prefill: open possible values in a new tab
  app/views/prefill_descriptions/_types_de_champs.html.haml
Labels: API

#8494 fix(only_present_on_draft?): broken when type_de_champ is removed from later revisions
  app/models/type_de_champ.rb
  spec/models/procedure_revision_spec.rb
Labels: bug

#8532 fix(dossier): fix parser with dashes
  app/models/concerns/tags_substitution_concern.rb
  spec/models/concern/tags_substitution_concern_spec.rb
Labels: bug

#8531 fix(menu): js error on click outside before unloading menu
  app/javascript/controllers/menu_button_controller.ts
Labels: bug

#8536 fix(instructeurs): filtre "Groupe instructeur" avec seulement les groupes de la démarche
  app/models/procedure_presentation.rb
  spec/models/procedure_presentation_spec.rb
Labels: bug
