Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2023-04, with the labels that each got.

#8842 fix(dossier): add value_json to dossier projection
  app/services/dossier_projection_service.rb
  spec/services/dossier_projection_service_spec.rb
Labels: bug

#8845 [bug] retirer les notifications + compteur des avis pour les dossiers terminés
  app/controllers/experts/avis_controller.rb
  app/models/avis.rb
  app/models/expert.rb
  spec/system/experts/expert_spec.rb
Labels: bug

#8847 fix(dossier): an invited user can remove (leave) a dossier
  app/controllers/users/dossiers_controller.rb
  app/models/user.rb
  app/views/users/dossiers/_dossier_actions.html.haml
  config/routes.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/models/user_spec.rb
  spec/system/users/list_dossiers_spec.rb
  spec/views/users/dossiers/_dossier_actions.html.haml_spec.rb
Labels: bug

#8853 fix(dossier): improuve commune champ rendering in pdf
  app/models/champs/commune_champ.rb
  app/views/dossiers/show.pdf.prawn
  spec/controllers/instructeurs/dossiers_controller_spec.rb
  spec/models/dossier_spec.rb
Labels: bug

#8846 fix(graphql): return better errors when dossiers cannot change state
  app/graphql/mutations/dossier_accepter.rb
  app/graphql/mutations/dossier_repasser_en_instruction.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
Labels: bug

#8863 fix(turbo): add getRootNode polyfill
  package.json
  yarn.lock
Labels: bug

#8864 fix(date): ne crash pas lorsqu'un champ date n'as pas une date standard
  app/models/champs/date_champ.rb
  spec/models/champs/date_champ_spec.rb
Labels: bug

#8868 fix(api-entreprise): do not crash when siret not found
  app/lib/api_entreprise/entreprise_adapter.rb
  app/lib/api_entreprise/rna_adapter.rb
Labels: bug

#8872 fix(dossier): selecting blank option should not empty selection
  app/models/champs/multiple_drop_down_list_champ.rb
  spec/models/champs/multiple_drop_down_list_champ_spec.rb
Labels: bug

#8873 fix(graphql): pendingDeletedSince should not crash
  app/models/dossier.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
Labels: bug

#8874 fix(dossier): instructeur actions should be buttons and not links
  app/views/instructeurs/dossiers/_header_actions.html.haml
  app/views/instructeurs/procedures/_dossier_actions.html.haml
  app/views/instructeurs/procedures/show.html.haml
  app/views/recherche/index.html.haml
  spec/system/instructeurs/instruction_spec.rb
  spec/views/instructeur/dossiers/show.html.haml_spec.rb
Labels: accessibilité

#8886 fix(admin): peut supprimer un admin sans démarche publiée, sans service
  app/models/administrateur.rb
  spec/models/administrateur_spec.rb
Labels: bug

#8891 fix link for csv example file
  app/views/administrateurs/groupe_instructeurs/_edit.html.haml
  config/locales/views/administrateurs/groupe_instructeurs/en.yml
  config/locales/views/administrateurs/groupe_instructeurs/fr.yml
Labels: bug

#8897 fix(dossier): delete all champs starting with children
  app/controllers/administrateurs/types_de_champ_controller.rb
  app/models/champ.rb
  app/models/dossier.rb
  app/models/procedure.rb
  spec/factories/dossier.rb
  spec/models/procedure_presentation_spec.rb
Labels: bug

#8920 ETQ instructeur, je veux voir l'état des dossiers affiché sur une seule ligne
  app/graphql/schema.graphql
  config/locales/models/dossier/en.yml
  config/locales/models/dossier/fr.yml
  spec/controllers/api/v2/graphql_controller_spec.rb
  spec/controllers/instructeurs/dossiers_controller_spec.rb
  spec/helpers/dossier_helper_spec.rb
  spec/models/procedure_presentation_spec.rb
  spec/views/instructeur/dossiers/show.html.haml_spec.rb
  spec/views/users/dossiers/show/_header.html.haml_spec.rb
Labels: bug

#8924 Tech: update rubocop, active nouveaux cops Rails/*
  .rubocop.yml
  Gemfile.lock
  app/controllers/ping_controller.rb
  app/controllers/support_controller.rb
  app/helpers/dossier_helper.rb
  app/jobs/cron/datagouv/account_by_month_job.rb
  app/jobs/cron/datagouv/administrateur_by_month_job.rb
  app/jobs/cron/datagouv/file_by_month_job.rb
  app/jobs/cron/datagouv/file_depose_by_month_job.rb
  app/jobs/cron/datagouv/instructeur_by_month_job.rb
  app/jobs/cron/datagouv/instructeur_connected_by_month_job.rb
  app/jobs/cron/datagouv/procedure_by_month_job.rb
  app/jobs/cron/datagouv/procedure_closed_by_month_job.rb
  app/jobs/cron/datagouv/procedure_deleted_by_month_job.rb
  app/jobs/cron/datagouv/user_connected_with_france_connect_by_month_job.rb
  app/lib/redcarpet/bare_renderer.rb
  app/models/avis.rb
  app/models/champs/multiple_drop_down_list_champ.rb
  app/models/commentaire.rb
  app/models/concerns/blob_virus_scanner_concern.rb
  app/models/concerns/procedure_stats_concern.rb
  app/models/dossier.rb
  app/models/etablissement.rb
  app/models/instructeur.rb
  app/models/procedure.rb
  app/models/traitement.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/prefill_repetition_type_de_champ.rb
  app/models/types_de_champ/prefill_type_de_champ.rb
  app/services/zxcvbn_service.rb
  app/views/dossiers/dossier_vide.pdf.prawn
  config/initializers/core_ext.rb
  lib/tasks/deployment/20210429172327_rename_conservation_extension.rake
  lib/tasks/deployment/20220922151100_populate_zones.rake
  lib/tasks/hotfix.rake
  spec/controllers/api/public/v1/dossiers_controller_spec.rb
  spec/controllers/api/public/v1/stats_controller_spec.rb
  spec/controllers/champs/piece_justificative_controller_spec.rb
  spec/controllers/ping_controller_spec.rb
  spec/controllers/webhook_controller_spec.rb
  spec/factories/procedure.rb
  spec/lib/tasks/graphql_spec.rb
  spec/models/procedure_spec.rb
  spec/services/dossier_projection_service_spec.rb
Labels: tech

#8930 ETQ usager, je voudrai pouvoir remplir un code postal avec des espaces
  app/models/champs/commune_champ.rb
  spec/models/champs/commune_champ_spec.rb
Labels: bug

#8938 bug(instructeurs.annotations): ETQ instructeurs, lorsque je saisie une autre valeur dans un champ de type choix simple, celle ci n'est pas sauvegardé
  app/controllers/instructeurs/dossiers_controller.rb
  spec/controllers/instructeurs/dossiers_controller_spec.rb
Labels: bug

#8937 ETQ administrateur, je m'attends a ce qu'au moins 3 répétition soient présentes dans le formulaire au format PDF
  app/views/dossiers/dossier_vide.pdf.prawn
Labels: bug

#8942 Correctif: corrige defaut_groupe_instructeur_id pour les procedures clonees (2023-04-17-01)
  app/models/procedure.rb
  lib/tasks/deployment/20230421091957_fix_defaut_groupe_instructeur_id_for_cloned_procedure.rake
  spec/models/procedure_spec.rb
Labels: bug

#8943 ETQ usager, je peux créer de nouveaux dossiers sur la démarche qui remplace la démarche fermée
  app/models/procedure.rb
  app/views/users/dossiers/_dossier_actions.html.haml
  spec/views/users/dossiers/_dossier_actions.html.haml_spec.rb
Labels: bug

#8944 ETQ super-admin je peux éditer l'attribut d'une démarche qui pointe vers la démarche qui la remplace
  app/dashboards/procedure_dashboard.rb
Labels: role:superadmin

#8934 ETQ utilisateur je ne veux pas perdre les _ au sein d'urls dans mes messages
  app/components/simple_format_component.rb
  app/lib/redcarpet/bare_renderer.rb
  spec/components/simple_format_component_spec.rb
Labels: bug

#8950 correctif(usager.depot-dossier): ETQ usager, les titres de section conditionnés sont visible meme si la condition n'est pas remplie
  app/components/editable_champ/header_section_component.rb
  app/components/editable_champ/header_section_component/header_section_component.html.haml
  spec/system/users/brouillon_spec.rb
Labels: bug

#8955 ETQ instructeur, je veux pouvoir accéder à mes annotations privées
  app/models/champs/header_section_champ.rb
  app/models/type_de_champ.rb
Labels: bug

#8964 ETQ Utilisateur, je ne veux pas de caractère invalide dans l'état du dossier en PDF
  app/views/dossiers/show.pdf.prawn
Labels: bug

#8954 Corrige la logic dans le cas de comparaise avec une liste de choix multiple
  lib/tasks/deployment/20230424154715_fix_include_in_logic.rake
  spec/lib/tasks/deployment/20230424154715_fix_include_in_logic.rake_spec.rb
Labels: bug, conditional

#8967 ETQ administrateur empêche une condition d'égalité de s'applique à un champ choix multiple
  app/components/types_de_champ_editor/conditions_errors_component.rb
  app/components/types_de_champ_editor/conditions_errors_component/conditions_errors_component.en.yml
  app/components/types_de_champ_editor/conditions_errors_component/conditions_errors_component.fr.yml
  app/models/logic/eq.rb
  spec/components/types_de_champ_editor/conditions_errors_component_spec.rb
  spec/models/logic/eq_spec.rb
  spec/models/logic/not_eq_spec.rb
Labels: bug, conditional

#8948 ETQ Usager, champ carte: ne permet pas d'enregistrer une geometry null pour ne pas casser les exports
  app/models/geo_area.rb
  app/validators/geo_json_validator.rb
  lib/tasks/deployment/20230421160218_fix_geo_area_without_geometry_again.rake
  spec/factories/geo_area.rb
  spec/models/geo_area_spec.rb
Labels: bug

#8968 Correctif: definit le groupe instructeur par defaut pour certaines procedure clonées
  app/models/procedure.rb
  spec/models/procedure_spec.rb
Labels: bug, feature:routage

#8962 ETQ usager utilisant microsoft Edge, les champs de type date sont mal alignés
  app/assets/stylesheets/forms.scss
Labels: bug

#8976 ETQ usager, je ne veux pas bypasser la vérification de SIRET
  app/controllers/users/dossiers_controller.rb
  app/models/procedure_revision.rb
  app/views/commencer/show.html.haml
  app/views/users/dossiers/etablissement.html.haml
  app/views/users/dossiers/index.html.haml
  spec/controllers/users/dossiers_controller_spec.rb
  spec/views/users/dossiers/index.html.haml_spec.rb
Labels: bug

#8961 ETQ usager, quand une les balises <select> avec une <option> ayant un libelle tres long, le select prends la largueur du contenu de l'option et force un scroll horizontal sur la page
  app/components/editable_champ/drop_down_list_component.rb
  app/components/editable_champ/drop_down_list_component/drop_down_list_component.html.haml
  app/components/editable_champ/section_component/section_component.html.haml
Labels: bug

#8978 Tech: ne mélange pas class & module Dolist, supprime adapter SMTP
  app/lib/dolist/api.rb
  app/lib/dolist/api_sender.rb
  app/lib/dolist/ignorable_error.rb
  app/models/email_event.rb
  config/env.example.optional
  config/environments/production.rb
  config/initializers/dolist.rb
Labels: tech

#8980 ETQ instructeur, je veux que tous les dossiers aient un demandeur
  lib/tasks/deployment/20230427090118_fix_dossiers_with_missing_identification.rake
Labels: bug

#8981 ETQ opérateur, je souhaite corriger des valeurs invalides de codes départementaux
  app/jobs/migrations/normalize_communes_job.rb
  lib/tasks/deployment/20230427094648_normalize_commune_code_departement.rake
  spec/jobs/migrations/normalize_communes_job_spec.rb
Labels: bug
