Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2024-12, with the labels that each got.

#11109 fix(dossier): when a champ type changes on update, ensure we have an instance of the right class
  app/models/concerns/dossier_champs_concern.rb
  spec/models/concerns/dossier_champs_concern_spec.rb
Labels: bug

#11099 ETQ instructeur je peux ajouter une colonne ou filtrer par des sous-valeurs d'un champ SIRET
  .gitignore
  .rubocop.yml
  app/assets/stylesheets/buttons.scss
  app/components/instructeurs/column_filter_component/column_filter_component.html.haml
  app/jobs/api_entreprise/entreprise_job.rb
  app/models/column.rb
  app/models/columns/json_path_column.rb
  app/models/concerns/addressable_column_concern.rb
  app/models/concerns/columns_concern.rb
  app/models/etablissement.rb
  app/models/types_de_champ/siret_type_de_champ.rb
  app/models/types_de_champ/type_de_champ_base.rb
  app/services/api_entreprise_service.rb
  app/tasks/maintenance/populate_siret_value_json_task.rb
  app/views/shared/dossiers/_identite_entreprise.html.haml
  config/locales/models/procedure_presentation/en.yml
  config/locales/models/procedure_presentation/fr.yml
  spec/factories/champ.rb
  spec/models/columns/champ_column_spec.rb
  spec/models/columns/dossier_column_spec.rb
  spec/models/concerns/columns_concern_spec.rb
  spec/models/etablissement_spec.rb
  spec/models/export_template_tabular_spec.rb
  spec/models/types_de_champ/siret_type_de_champ_spec.rb
  spec/services/dossier_filter_service_spec.rb
  spec/services/dossier_projection_service_spec.rb
  spec/system/instructeurs/procedure_filters_spec.rb
  spec/tasks/maintenance/populate_siret_value_json_task_spec.rb
  spec/views/shared/dossiers/_normalized_address.html.haml_spec.rb
Labels: role:instructeur, a-communiquer-instances

#11127 fix(champ): always check if a champ is in dossier revision before validate
  app/controllers/champs/piece_justificative_controller.rb
  app/models/champ.rb
  app/models/champs/boolean_champ.rb
  app/models/champs/civilite_champ.rb
  app/models/champs/cnaf_champ.rb
  app/models/champs/commune_champ.rb
  app/models/champs/decimal_number_champ.rb
  app/models/champs/departement_champ.rb
  app/models/champs/dgfip_champ.rb
  app/models/champs/drop_down_list_champ.rb
  app/models/champs/email_champ.rb
  app/models/champs/engagement_juridique_champ.rb
  app/models/champs/epci_champ.rb
  app/models/champs/expression_reguliere_champ.rb
  app/models/champs/iban_champ.rb
  app/models/champs/integer_number_champ.rb
  app/models/champs/multiple_drop_down_list_champ.rb
  app/models/champs/phone_champ.rb
  app/models/champs/piece_justificative_champ.rb
  app/models/champs/region_champ.rb
  app/models/champs/rna_champ.rb
  app/models/champs/titre_identite_champ.rb
  app/models/concerns/champ_validate_concern.rb
  spec/factories/dossier.rb
  spec/models/champs/dossier_link_champ_spec.rb
  spec/models/champs/epci_champ_spec.rb
  spec/models/champs/piece_justificative_champ_spec.rb
  spec/models/concerns/champ_validate_concern_spec.rb
  spec/models/dossier_spec.rb
  spec/models/prefill_champs_spec.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
Labels: bug

#11094 ETQ admin, corrige l'affichage dans le récap de modifications d'une erreur existant dans l'attestation v2
  app/components/procedure/card/attestation_component.rb
  app/components/procedure/errors_summary.rb
  app/controllers/administrateurs/procedures_controller.rb
  spec/components/procedures/errors_summary_spec.rb
  spec/system/administrateurs/procedure_attestation_template_spec.rb
Labels: bug, administrateurs

#11108 ETQ admin, corrige l'intitulé de la direction de l'attestation pour s'aligner à droite quand il y a plusieurs lignes
  app/assets/stylesheets/attestation.scss
Labels: bug, attestation v2

#11131 ETQ usager corrige le fait d'être informé d'un dossier inéligible dans certaines conditions
  app/components/dossiers/autosave_footer_component/autosave_footer_component.en.yml
  app/components/dossiers/autosave_footer_component/autosave_footer_component.fr.yml
  app/components/dossiers/autosave_footer_component/autosave_footer_component.html.haml
  app/components/dossiers/invalid_ineligibilite_rules_component.rb
  app/components/dossiers/invalid_ineligibilite_rules_component/invalid_ineligibilite_rules_component.html.haml
  app/components/procedure/pending_republish_component/pending_republish_component.html.haml
  app/controllers/administrateurs/ineligibilite_rules_controller.rb
  app/controllers/users/dossiers_controller.rb
  app/javascript/controllers/autosave_controller.ts
  app/javascript/controllers/ineligibilite_rules_match_controller.ts
  app/models/concerns/dossier_clone_concern.rb
  app/models/dossier.rb
  app/views/users/dossiers/update.turbo_stream.haml
  spec/components/dossiers/autosave_footer_component_spec.rb
  spec/controllers/administrateurs/ineligibilite_rules_controller_spec.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/system/users/dossier_ineligibilite_spec.rb
  spec/views/shared/dossiers/_edit.html.haml_spec.rb
Labels: bug

#11144 fix(dossier): on fork merge, always remove previous champ version
  app/models/concerns/dossier_clone_concern.rb
  app/tasks/maintenance/t20241216remove_non_unique_champs_task.rb
  spec/models/concerns/dossier_clone_concern_spec.rb
  spec/tasks/maintenance/t20241216remove_non_unique_champs_task_spec.rb
Labels: bug

#11146 ETQ usager, footer sticky du formulaire plus adapté sur mobile et/ou pour dossier inéligible
  app/assets/stylesheets/autosave.scss
  app/assets/stylesheets/dossier_edit.scss
  app/components/dossiers/autosave_footer_component/autosave_footer_component.html.haml
  app/components/dossiers/edit_footer_component.rb
  app/views/users/dossiers/modifier.html.haml
Labels: role:usager

#11013 ETQ admin je suis informé des infos remontées par le champ SIRET
  app/assets/stylesheets/flex.scss
  app/components/dossiers/invalid_ineligibilite_rules_component/invalid_ineligibilite_rules_component.en.yml
  app/components/dossiers/invalid_ineligibilite_rules_component/invalid_ineligibilite_rules_component.fr.yml
  app/components/dossiers/invalid_ineligibilite_rules_component/invalid_ineligibilite_rules_component.html.haml
  app/components/types_de_champ_editor/champ_component/champ_component.html.haml
  app/controllers/administrateurs/procedures_controller.rb
  app/javascript/controllers/lazy_modal_controller.ts
  app/models/concerns/columns_concern.rb
  app/models/etablissement.rb
  app/views/administrateurs/procedures/api_champ_columns.html.haml
  app/views/administrateurs/procedures/champs.html.haml
  app/views/layouts/_display_theme_modal.html.haml
  app/views/layouts/_header.haml
  app/views/layouts/_search_dossiers_form.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/views/administrateurs/procedures/en.yml
  config/locales/views/administrateurs/procedures/fr.yml
  config/routes.rb
  spec/system/administrateurs/types_de_champ_spec.rb
Labels: administrateurs

#11126 ETQ usager, pas d'erreur inutile lors d'un double callback FranceConnect
  app/models/france_connect_information.rb
  spec/models/france_connect_information_spec.rb
Labels: bug

#11151 ETQ Invité, je ne peux pas soumettre de correction sur un dossier déposé
  app/components/dossiers/edit_footer_component.rb
  app/controllers/users/dossiers_controller.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/system/users/invite_spec.rb
Labels: role:usager

#10991 ETQ usager, je veux que les erreurs et les descriptions soient reliées aux champs concernés
  app/assets/stylesheets/forms.scss
  app/components/attachment/edit_component.rb
  app/components/attachment/edit_component/edit_component.html.haml
  app/components/dsfr/input_errorable.rb
  app/components/dsfr/input_status_message_component.rb
  app/components/dsfr/input_status_message_component/input_status_message_component.html.haml
  app/components/editable_champ/champ_label_component/champ_label_component.html.haml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
  app/components/editable_champ/checkbox_component/checkbox_component.html.haml
  app/components/editable_champ/cnaf_component/cnaf_component.html.haml
  app/components/editable_champ/communes_component.rb
  app/components/editable_champ/communes_component/communes_component.html.haml
  app/components/editable_champ/date_component/date_component.html.haml
  app/components/editable_champ/datetime_component/datetime_component.html.haml
  app/components/editable_champ/decimal_number_component/decimal_number_component.html.haml
  app/components/editable_champ/departements_component/departements_component.html.haml
  app/components/editable_champ/dgfip_component/dgfip_component.html.haml
  app/components/editable_champ/dossier_link_component/dossier_link_component.html.haml
  app/components/editable_champ/drop_down_list_component.rb
  app/components/editable_champ/drop_down_list_component/drop_down_list_component.html.haml
  app/components/editable_champ/editable_champ_base_component.rb
  app/components/editable_champ/editable_champ_component.rb
  app/components/editable_champ/editable_champ_component/editable_champ_component.html.haml
  app/components/editable_champ/email_component/email_component.html.haml
  app/components/editable_champ/engagement_juridique_component/engagement_juridique_component.html.haml
  app/components/editable_champ/epci_component/epci_component.html.haml
  app/components/editable_champ/expression_reguliere_component/expression_reguliere_component.html.haml
  app/components/editable_champ/iban_component/iban_component.html.haml
  app/components/editable_champ/integer_number_component/integer_number_component.html.haml
  app/components/editable_champ/linked_drop_down_list_component/linked_drop_down_list_component.html.haml
  app/components/editable_champ/mesri_component/mesri_component.html.haml
  app/components/editable_champ/multiple_drop_down_list_component.rb
  app/components/editable_champ/multiple_drop_down_list_component/multiple_drop_down_list_component.html.haml
  app/components/editable_champ/number_component/number_component.html.haml
  app/components/editable_champ/pays_component/pays_component.html.haml
  app/components/editable_champ/phone_component/phone_component.html.haml
  app/components/editable_champ/pole_emploi_component/pole_emploi_component.html.haml
  app/components/editable_champ/regions_component/regions_component.html.haml
  app/components/editable_champ/repetition_component/repetition_component.html.haml
  app/components/editable_champ/rna_component/rna_component.html.haml
  app/components/editable_champ/rnf_component/rnf_component.html.haml
  app/components/editable_champ/siret_component/siret_component.html.haml
  app/components/editable_champ/text_component/text_component.html.haml
  app/components/editable_champ/textarea_component/textarea_component.html.haml
  app/javascript/components/ComboBox.tsx
  app/javascript/components/react-aria/hooks.ts
  app/models/champ.rb
  spec/components/attachment/edit_component_spec.rb
  spec/components/editable_champ/communes_component_spec.rb
  spec/components/editable_champ/drop_down_list_component_spec.rb
Labels: accessibilité

#11163 ETQ admin je suis informé que je ne peux pas activer le SVA/SVR si la démarche est déclarative et vice-versa
  app/components/procedure/sva_svr_form_component.rb
  app/components/procedure/sva_svr_form_component/sva_svr_form_component.en.yml
  app/components/procedure/sva_svr_form_component/sva_svr_form_component.fr.yml
  app/components/procedure/sva_svr_form_component/sva_svr_form_component.html.haml
  app/controllers/administrateurs/sva_svr_controller.rb
  app/views/administrateurs/procedures/_informations.html.haml
  spec/components/procedures/sva_svr_form_component_spec.rb
Labels: administrateurs
