Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2024-04, with the labels that each got.

#10248 chore(js): use bun instead of yarn
  .github/actions/ci-save-split-tests/action.yml
  .github/actions/ci-setup-assets/action.yml
  .github/actions/ci-setup-rails/action.yml
  .github/actions/ci-setup-split-tests/action.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/git.yml
  .github/workflows/rails_schema_check.yml
  README.md
  bin/setup
  bin/update
  bin/yarn
  bun.lockb
  doc/DEPLOYMENT.md
  lib/tasks/lint.rake
  package.json
  yarn.lock
Labels: a-communiquer-instances

#10232 Correctif: redirige la page fermeture vers la page commencer si la démarche n'est pas fermée
  app/controllers/users/commencer_controller.rb
Labels: bug

#10230 Correctif : affiche correctement le lien vers la page de fermeture dans la liste des dossiers
  app/views/users/dossiers/_dossiers_list.html.haml
  config/locales/en.yml
  config/locales/fr.yml
Labels: bug

#10272 fix(champ): do not validate hidden champs
  app/models/champ.rb
  spec/models/champs/checkbox_champ_spec.rb
  spec/models/champs/cnaf_champ_spec.rb
  spec/models/champs/dgfip_champ_spec.rb
  spec/models/champs/yes_no_champ_spec.rb
  spec/models/concern/champ_conditional_concern_spec.rb
Labels: bug

#10171 perf(filter): we query by stable_id - no need to check type_de_champ private attribute
  app/models/dossier.rb
  app/models/procedure_presentation.rb
Labels: performances

#10282 fix(adresse): fallback to city name if commune not found
  app/services/api_geo_service.rb
  spec/services/api_geo_service_spec.rb
Labels: bug

#10283 Remplacement de l'attribut `aria-current="page"` par `aria-current="true"` lorsque le lien concerne un ensemble de pages
  app/components/main_navigation/instructeur_expert_navigation_component.rb
  app/views/administrateurs/_main_navigation.html.haml
  app/views/users/_main_navigation.html.haml
  spec/components/main_navigation/instructeur_expert_navigation_component_spec.rb
Labels: accessibilité

#10305 fix(schema): drop bulk_messages_groupe_instructeurs
  db/migrate/20240411164502_drop_bulk_messages_groupe_instructeurs.rb
  db/schema.rb
Labels: bug

#10315 ETQ usager : pas d'`aria-invalid`
  app/components/dsfr/input_errorable.rb
Labels: accessibilité

#10314 ETQ Usager je souhaite que le champ carte soit plus accessible
  app/assets/stylesheets/forms.scss
  app/components/dsfr/input_errorable.rb
  app/components/editable_champ/carte_component.rb
  app/components/editable_champ/carte_component/carte_component.html.haml
  app/javascript/components/MapEditor/components/AddressInput.tsx
  app/javascript/components/MapEditor/index.tsx
  app/models/champs/carte_champ.rb
  config/locales/models/champs/carte_champ/en.yml
  config/locales/models/champs/carte_champ/fr.yml
Labels: accessibilité

#10323 fix(commune): no crash on blank codes
  app/services/api_geo_service.rb
  spec/services/api_geo_service_spec.rb
Labels: bug

#10325 Tech: pas d'erreur si un usager essaie d'ajouter une ligne d'un champ répétition sans enfant
  app/controllers/champs/repetition_controller.rb
Labels: bug

#10336 Usager: fix champ adresse dans un TOM sans code postal dans la BAN (ex. Nouvelle-Calédonie à Nouméa)
  app/models/champs/address_champ.rb
  app/services/api_geo_service.rb
  spec/models/champs/address_champ_spec.rb
  spec/services/api_geo_service_spec.rb
Labels: bug

#10317 ETQ Usager, je souhaite que mon screen reader verbalise les erreurs sur les champs unique contenu dans un `fieldset`
  app/components/dsfr/input_errorable.rb
  app/components/dsfr/input_status_message_component.rb
  app/components/dsfr/input_status_message_component/input_status_message_component.html.haml
  app/components/editable_champ/editable_champ_component.rb
  app/components/editable_champ/editable_champ_component/editable_champ_component.html.haml
  app/models/champ.rb
Labels: accessibilité
