Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2024-11, with the labels that each got.

#10993 ETQ usager, je veux que le titre du modèle de pièce jointe reprenne l'intitulé visible
  app/components/dsfr/download_component.rb
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.en.yml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.fr.yml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
  app/views/shared/_piece_justificative_template.html.haml
  config/locales/models/champs/carte_champ/en.yml
  config/locales/models/champs/decimal_number_champ/en.yml
  config/locales/models/champs/iban_champ/en.yml
  config/locales/models/champs/phone_champ/en.yml
  config/locales/models/champs/rna_champ/en.yml
  config/locales/models/champs/siret_champ/en.yml
  config/locales/views/shared/en.yml
  config/locales/views/shared/fr.yml
  spec/components/editable_champ/piece_justificative_component/piece_justificative_component_spec.rb
Labels: accessibilité

#11009 ETQ usager utilisant un lecteur d'écran, je veux être informé du résultat retourné par la recherche d'un numéro RNF
  app/components/editable_champ/rnf_component/rnf_component.en.yml
  app/components/editable_champ/rnf_component/rnf_component.fr.yml
  app/components/editable_champ/rnf_component/rnf_component.html.haml
  app/views/shared/champs/rna/_association.html.haml
  config/locales/models/champs/rnf_champ/en.yml
  config/locales/models/champs/rnf_champ/fr.yml
  config/locales/shared.en.yml
  config/locales/shared.fr.yml
Labels: accessibilité

#11003 ETQ usager, utilisant un lecteur d'écran je veux être informé du nombre de caractères restants ou en trop dans un textarea
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
  app/components/editable_champ/textarea_component/textarea_component.en.yml
  app/components/editable_champ/textarea_component/textarea_component.fr.yml
  app/components/editable_champ/textarea_component/textarea_component.html.haml
  config/locales/models/champs/decimal_number_champ/en.yml
  config/locales/models/champs/decimal_number_champ/fr.yml
Labels: accessibilité

#11022 ETQ dev, je souhaite ignorer les erreurs MiniMagick connues
  app/jobs/image_processor_job.rb
Labels: bug

#11034 Instructeur: corrige l'affichage de données api dans le tableau d'une démarche
  app/services/dossier_projection_service.rb
  spec/services/dossier_projection_service_spec.rb
Labels: bug

#11040 ETQ Instructeur: cache la colonne de filtrage décision avant du SVA/SVR
  app/models/procedure_presentation.rb
Labels: bug

#11046 fix(champ): do not validate champs with changed type
  app/models/concerns/champs_validate_concern.rb
  spec/models/concerns/champs_validate_concern_spec.rb
Labels: bug

#11054 fix(champ): no crash when drop_down_list with other champ value_json is nil
  app/models/types_de_champ/drop_down_list_type_de_champ.rb
Labels: bug

#11052 ETQ instructeur: modification de l'id de column liste liée pour faire satisfaire le waf
  app/models/columns/linked_drop_down_column.rb
  app/models/concerns/columns_concern.rb
  spec/models/concerns/columns_concern_spec.rb
Labels: bug, role:instructeur

#11074 ETQ Usager, je veux recevoir des mails !
  app/models/user.rb
  spec/system/users/sign_up_spec.rb
Labels: bug, role:usager
