Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2024-10, with the labels that each got.

#10822 Corrige les défaut d'accessibilité de la page de création de compte accessibilité
  app/components/dossiers/individual_form_component/individual_form_component.html.haml
  app/javascript/controllers/email_input_controller.ts
  app/views/devise/passwords/new.html.haml
  app/views/france_connect/particulier/confirmation_sent.html.haml
  app/views/layouts/_header.haml
  app/views/users/confirmations/new.html.haml
  app/views/users/dossiers/index.html.haml
  app/views/users/registrations/new.html.haml
  app/views/users/sessions/link_sent.html.haml
  app/views/users/sessions/new.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/metas.en.yml
  config/locales/metas.fr.yml
  spec/views/users/dossiers/index.html.haml_spec.rb
Labels: accessibilité

#10879 Corrige les défaut d'accessibilité de l'étape 1 d'une démarche
  app/assets/stylesheets/buttons.scss
  app/components/dossiers/individual_form_component/individual_form_component.html.haml
  app/components/dossiers/user_procedure_filter_component/user_procedure_filter_component.html.haml
  app/views/layouts/_header.haml
  app/views/layouts/commencer/_no_procedure.html.haml
  app/views/root/landing.html.haml
  app/views/users/_main_navigation.html.haml
  app/views/users/dossiers/identite.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/metas.en.yml
  config/locales/metas.fr.yml
Labels: accessibilité

#10886 ETQ super-admin, corrige l'affichage de certains boutons d'actions dans le manager
  app/views/manager/instructeurs/show.html.erb
  app/views/manager/outdated_procedures/_collection.html.erb
  app/views/manager/outdated_procedures/index.html.erb
  app/views/manager/procedures/show.html.erb
  app/views/manager/published_procedures/index.html.erb
Labels: bug

#10894 fix(dossier): projected champs should have updated_at
  app/models/concerns/dossier_champs_concern.rb
  spec/models/concerns/dossier_champs_concern_spec.rb
Labels: bug

#10888 ETQ tech, on souhaite tout passer sur sidekiq
  Procfile.dev
  app/jobs/sidekiq_again_job.rb
  config/env.example.optional
  config/environments/production.rb
  config/initializers/transition_to_sidekiq.rb
Labels: a-communiquer-instances

#10930 ETQ instructeur je peux filtrer un champ "choix simple" avec un long libellé d'option
  app/models/procedure_presentation.rb
  spec/controllers/instructeurs/procedures_controller_spec.rb
  spec/models/procedure_presentation_spec.rb
Labels: bug

#10942 Correctif : ETQ admin je peux importer des groupes d'instructeurs
  app/components/procedure/groupes_management_component/groupes_management_component.html.haml
Labels: bug

#10956 ETQ Instructeur, je peux à nouveau filtrer sur les types de champ choix multiple
  app/components/instructeurs/column_filter_component/column_filter_component.html.haml
  app/models/concerns/dossier_filtering_concern.rb
  app/models/type_de_champ.rb
  app/services/dossier_filter_service.rb
  config/brakeman.ignore
  spec/services/dossier_filter_service_spec.rb
Labels: bug

#10893 Améliore la restitution des message d'erreur lors d'une soumission en erreur
  app/components/dossiers/errors_full_messages_component/errors_full_messages_component.en.yml
  app/components/dossiers/errors_full_messages_component/errors_full_messages_component.fr.yml
  app/components/dossiers/errors_full_messages_component/errors_full_messages_component.html.haml
  app/javascript/controllers/autofocus_controller.ts
  app/views/shared/dossiers/_header.html.haml
  app/views/users/dossiers/show/_header.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/views/users/dossiers/demande.html.haml_spec.rb
  spec/views/users/dossiers/show.html.haml_spec.rb
  spec/views/users/dossiers/show/_header.html.haml_spec.rb
Labels: accessibilité

#10969 fix(dossier): fix preloader with champs outside of revision
  app/models/dossier_preloader.rb
Labels: bug

#10985 fix(email-checker): success can have no suggestions
  app/javascript/controllers/email_input_controller.ts
Labels: bug

#10965 Restitution des bandeau de statut (erreur ou succès)
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/notifications.scss
  app/components/dossiers/batch_operation_component/batch_operation_component.html.haml
  app/components/dropdown/menu_component/menu_component.html.haml
  app/components/dsfr/input_status_message_component/input_status_message_component.html.haml
  app/components/editable_champ/champ_label_content_component/champ_label_content_component.html.haml
  app/helpers/application_helper.rb
  app/views/invites/_dropdown.html.haml
  app/views/invites/_form.html.haml
  app/views/layouts/_flash_messages.html.haml
  app/views/layouts/_header.haml
  app/views/layouts/application.turbo_stream.haml
  config/locales/metas.en.yml
  config/locales/metas.fr.yml
  public/500.html
  public/502.html
  public/503.html
  public/504.html
  spec/support/system_helpers.rb
  spec/system/users/brouillon_spec.rb
Labels: accessibilité
