Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2024-02, with the labels that each got.

#9965 ETQ usager je peux saisir un numéro RNA valide qui ne contient pas que des chiffres
  app/components/editable_champ/rna_component/rna_component.fr.yml
  app/models/champs/rna_champ.rb
  app/views/shared/champs/rna/_association.html.haml
  spec/controllers/champs/rna_controller_spec.rb
Labels: bug

#9963 Tech: fix maintenance task invokation `AddDossiersMissingChampsTask`
  app/tasks/maintenance/add_dossiers_missing_champs_task.rb
Labels: bug

#9974 ETQ usager je vois de nouveau le délai d'instruction pour les démarches déclaratives en instruction
  app/components/procedure/estimated_delay_component.rb
Labels: bug

#9983 ETQ instructeur: fix génération d'attestation avec une balise "nom de la commune" depuis un champ adresse
  app/models/champs/address_champ.rb
  spec/models/champs/address_champ_spec.rb
Labels: bug

#9985 ETQ Usager, je ne veux pas voir un message d'alerte indiquant que la démarche est close lorsque je modifie un dossier en construction
  app/helpers/dossier_helper.rb
  spec/helpers/dossier_helper_spec.rb
Labels: bug

#9987 ETQ Usager, je veux trouver ma commune qui est trop bas dans la liste des résultats
  app/components/dsfr/combobox_component.rb
  app/components/dsfr/combobox_component/combobox_component.html.haml
  app/components/editable_champ/communes_component/communes_component.html.haml
  app/controllers/data_sources/commune_controller.rb
  app/javascript/controllers/combobox_controller.ts
  app/javascript/shared/combobox-ui.ts
  app/javascript/shared/combobox.ts
  spec/fixtures/cassettes/communes.yml
Labels: bug

#9993 Tech: supprime CSP_REPORT_URI env var et configuration
  config/env.example.optional
  config/initializers/02_urls.rb
  config/initializers/content_security_policy.rb
Labels: a-communiquer-instances

#10008 ETQ admin: correction du cache de la liste des PJ d'une démarche en brouillon
  app/views/shared/_procedure_description.html.haml
  spec/views/shared/_procedure_description.html.haml_spec.rb
Labels: bug

#10019 ETQ uager, fix sélection d'un choix multiple qui commence par `[`
  app/models/champs/multiple_drop_down_list_champ.rb
  spec/models/champs/multiple_drop_down_list_champ_spec.rb
Labels: bug

#10021 ETQ usager je dois voir de vraies apostrophes à la place de `&#39;` dans les sujets d'email
  app/models/concerns/mail_template_concern.rb
  spec/mailers/notification_mailer_spec.rb
Labels: bug

#10018 fix(champ): do not reset data on champs without fetch_external_data
  app/components/editable_champ/address_component/address_component.html.haml
  app/javascript/shared/combobox-ui.ts
  app/models/champ.rb
  app/models/champs/address_champ.rb
  spec/fixtures/cassettes/The_user/fill_a_dossier.yml
  spec/fixtures/cassettes/communes.yml
  spec/models/champ_spec.rb
  spec/system/users/brouillon_spec.rb
Labels: bug

#10014 ETQ expert: je retrouve mes avis confidentiel dans les exports. ETQ instructeur, je retrouve les fichiers joint a une demande d'avis expert
  app/services/pieces_justificatives_service.rb
  spec/services/pieces_justificatives_service_spec.rb
Labels: a-communiquer

#10024 Tech: cache le bouton de c/c lorsque le navigateur bloque l'accès au clipboard
  app/javascript/controllers/clipboard_controller.ts
Labels: bug

#10025 ETQ instructeur, message d'erreur plutôt que crash lorsqu'on ajoute un filtre trop long (plus de 100 caractères)
  app/controllers/instructeurs/procedures_controller.rb
  app/models/procedure_presentation.rb
  spec/controllers/instructeurs/procedures_controller_spec.rb
Labels: bug

#10012 Tech: document STRICT_EMAIL_VALIDATION_STARTS_ON env var
  config/env.example
  spec/mailers/groupe_gestionnaire_mailer_spec.rb
  spec/mailers/groupe_instructeur_mailer_spec.rb
  spec/services/dossier_projection_service_spec.rb
Labels: a-communiquer-instances

#10032 API: fix régression d'accès aux attestations PDF
  app/controllers/api/v2/dossiers_controller.rb
Labels: bug

#10035 Tech: supprime support de mailjet
  Gemfile
  Gemfile.lock
  app/controllers/manager/users_controller.rb
  app/lib/mailjet/api.rb
  app/mailers/instructeur_mailer.rb
  app/views/manager/users/emails.html.erb
  config/env.example
  config/environments/production.rb
  config/initializers/mailjet.rb
  config/secrets.yml
  spec/controllers/api/v2/graphql_controller_spec.rb
Labels: bug

#10052 fix(export): do not crash when dossier user is deleted
  app/models/dossier.rb
Labels: bug
