Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2024-09, with the labels that each got.

#10680 Refonte du menu d'aide
  app/assets/stylesheets/buttons.scss
  app/assets/stylesheets/help_dropdown.scss
  app/views/shared/help/_help_dropdown_dossier.html.haml
  app/views/shared/help/_help_dropdown_instructeur.html.haml
  app/views/shared/help/_help_dropdown_procedure.html.haml
  app/views/shared/help/dropdown_items/_email_item.html.haml
  app/views/shared/help/dropdown_items/_faq_item.html.haml
  app/views/shared/help/dropdown_items/_messagerie_item.html.haml
  app/views/shared/help/dropdown_items/_service_item.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/system/accessibilite/wcag_usager_spec.rb
  spec/system/help_spec.rb
  spec/views/layouts/_header_spec.rb
Labels: bug, accessibilité

#10736 Correctif: lors de l‘import en masse d'instructeurs, les nouveaux instructeurs reçoivent un lien pour vérifier leur email
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  spec/controllers/administrateurs/groupe_instructeurs_controller_spec.rb
  spec/fixtures/files/two-instructeurs-file.csv
Labels: bug

#10838 Ajoute la vocalisation du composant d'analyse de complexicité du mot de passe pour les technologies d'assistance
  app/components/instructeurs/activate_account_form_component/activate_account_form_component.html.haml
  app/components/password_complexity_component/password_complexity_component.html.haml
  app/views/administrateurs/activate/new.html.haml
  app/views/devise/passwords/edit.html.haml
  app/views/experts/avis/sign_up.html.haml
  app/views/gestionnaires/activate/new.html.haml
  app/views/users/registrations/new.html.haml
Labels: accessibilité

#10849 fix(combobox): can copy past multiple values in restricted multi select combobox
  app/components/editable_champ/multiple_drop_down_list_component.rb
  app/components/instructeurs/column_picker_component/column_picker_component.html.haml
  app/javascript/components/ComboBox.tsx
  app/javascript/components/react-aria/hooks.ts
  app/javascript/components/react-aria/props.ts
  spec/system/instructeurs/expert_spec.rb
Labels: bug

#10862 ETQ usager: corrige la date prévisionnelle SVA lorsqu'il y a un mélange de demandes de corrections résolues et en attente
  app/services/sva_svr_decision_date_calculator_service.rb
  spec/services/sva_svr_decision_date_calculator_service_spec.rb
Labels: bug
