Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2025-03, with the labels that each got.

#11391 fix(gallery): do not show in gallery hidden pieces justificatives
  app/controllers/instructeurs/dossiers_controller.rb
Labels: bug

#11385 ETQ Usager ayant des difficultés à saisir du contenu, je veux que les champs me proposent l'autocompletion
  app/components/editable_champ/email_component/email_component.html.haml
  app/components/editable_champ/pays_component/pays_component.html.haml
  app/components/editable_champ/phone_component/phone_component.html.haml
  app/views/users/dossiers/transferer.html.haml
Labels: accessibilité

#11384 ETQ instructeur la clôture auto d'une démarche laisse les dossiers en attente de correction en construction
  app/jobs/auto_archive_procedure_dossiers_job.rb
  app/models/dossier.rb
  app/tasks/maintenance/t20250226_fix_dossiers_en_instruction_with_pending_correction_task.rb
  spec/jobs/auto_archive_procedure_dossiers_job_spec.rb
  spec/models/dossier_spec.rb
  spec/tasks/maintenance/t20250226_fix_dossiers_en_instruction_with_pending_correction_task_spec.rb
Labels: bug

#11338 ETQ usager, je veux que la hiérarchie de titres d'une demande soit correcte
  app/assets/stylesheets/forms.scss
  app/assets/stylesheets/message.scss
  app/assets/stylesheets/sections.scss
  app/components/editable_champ/header_section_component.rb
  app/components/editable_champ/repetition_row_component/repetition_row_component.html.haml
  app/views/shared/dossiers/_header.html.haml
Labels: bug, accessibilité

#11407 ETQ usager du champ formaté, je ne veux pas voir le format du mode avancé quand c'est le mode simple
  app/components/editable_champ/champ_label_component/champ_label_component.html.haml
  app/components/editable_champ/formatted_component/formatted_component.html.haml
  app/models/champ.rb
  app/models/type_de_champ.rb
  app/models/types_de_champ/formatted_type_de_champ.rb
  spec/factories/type_de_champ.rb
  spec/models/type_de_champ_spec.rb
Labels: bug

#11440 ETQ usager, corrige les erreurs 404 en construction quand la révision est passée à un champ référentiel
  app/models/champs/drop_down_list_champ.rb
  spec/models/champs/drop_down_list_champ_spec.rb
Labels: bug

#11438 ETQ usager fix liste des dossiers quand une procédure qui en remplace une autre a été supprimée
  app/views/users/dossiers/_dossiers_list.html.haml
Labels: bug

#11348 ETQ Usager, je veux que l'intitulé des champs email soit le même partout
  app/components/dsfr/input_component/input_component.fr.yml
  app/components/procedure/import_component/import_component.fr.yml
  app/mailers/user_mailer.rb
  app/views/devise_mailer/email_changed.html.haml
  app/views/shared/dossiers/_mandataire_infos.html.haml
  app/views/shared/dossiers/_user_infos.html.haml
  config/locales/api_particulier.fr.yml
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/models/champs/rnf_champ/fr.yml
  config/locales/models/dossier_transfer/fr.yml
  config/locales/models/groupe_gestionnaire/fr.yml
  config/locales/models/individual/fr.yml
  config/locales/models/instructeur/fr.yml
  config/locales/models/procedure/fr.yml
  config/locales/models/procedure_presentation/fr.yml
  config/locales/models/service/fr.yml
  config/locales/views/administrateurs/groupe_instructeurs/fr.yml
  config/locales/views/contact/fr.yml
  config/locales/views/instructeurs/groupe_instructeurs/fr.yml
  config/locales/views/manager/fr.yml
  config/locales/views/users/dossier_transfer/fr.yml
  config/locales/views/users/profil/fr.yml
  doc/faqs/administrateur/ajouter-plusieurs-administrateurs-sur-une-meme-demarche.fr.md
  doc/faqs/administrateur/comment-obtenir-un-compte-administrateur.fr.md
  doc/faqs/administrateur/guide-de-bonnes-pratiques-pour-tester-une-demarche.fr.md
  doc/faqs/administrateur/je-ne-trouve-pas-ma-demarche-dans-le-catalogue-de-demarches.fr.md
  doc/faqs/administrateur/les-instructeurs-n-ont-pas-recu-d-email-d-invitation.fr.md
  doc/faqs/instructeur/je-n-arrive-pas-a-acceder-aux-dossiers-que-je-souhaite-instruire.fr.md
  doc/faqs/usager/01_comment-trouver-ma-demarche.fr.md
  doc/faqs/usager/j-ai-depose-moi-meme-mon-dossier-mais-je-ne-le-retrouve-pas.fr.md
  doc/faqs/usager/je-ne-recois-pas-d-email.fr.md
  doc/faqs/usager/je-veux-changer-mon-adresse-email.fr.md
  doc/faqs/usager/je-veux-changer-mon-mot-de-passe.fr.md
  doc/faqs/usager/je-veux-contacter-le-service-en-charge-de-ma-demarche.fr.md
  doc/faqs/usager/mon-dossier-a-ete-depose-par-un-tiers-et-je-souhaite-y-acceder.fr.md
  spec/components/procedures/errors_summary_spec.rb
  spec/controllers/api/v2/graphql_controller_stored_queries_spec.rb
  spec/controllers/contact_controller_spec.rb
  spec/controllers/faq_controller_spec.rb
  spec/controllers/france_connect/particulier_controller_spec.rb
  spec/controllers/manager/dossiers_controller_spec.rb
  spec/controllers/users/profil_controller_spec.rb
  spec/controllers/users/transfers_controller_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/columns/dossier_column_spec.rb
  spec/models/concerns/columns_concern_spec.rb
  spec/models/export_template_tabular_spec.rb
  spec/services/procedure_export_service_tabular_spec.rb
  spec/system/api_particulier/api_particulier_spec.rb
  spec/system/france_connect/france_connect_particulier_spec.rb
  spec/system/users/dossier_creation_spec.rb
  spec/system/users/dossier_prefill_get_spec.rb
  spec/system/users/dossier_prefill_post_spec.rb
  spec/system/users/transfer_dossier_spec.rb
Labels: bug, accessibilité

#11354 ETQ utilisateur d'un lecteur d'écran, je veux que les messages d'alertes/d'info me soient restitués
  app/controllers/attachments_controller.rb
  app/views/attachments/destroy.turbo_stream.haml
  app/views/layouts/_flash_messages.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/system/users/brouillon_spec.rb
  spec/system/users/en_construction_spec.rb
Labels: bug, accessibilité

#11376 ETQ Usager, je veux que les aides à la saisie et les messages d'erreurs soient plus clairs
  app/components/attachment/edit_component/edit_component.en.yml
  app/components/attachment/edit_component/edit_component.fr.yml
  app/components/editable_champ/linked_drop_down_list_component/linked_drop_down_list_component.html.haml
  app/models/champs/email_champ.rb
  config/locales/en.yml
  config/locales/fr.yml
  config/locales/models/champs/commune_champ/en.yml
  config/locales/models/champs/commune_champ/fr.yml
  config/locales/models/champs/decimal_number_champ/en.yml
  config/locales/models/champs/decimal_number_champ/fr.yml
  config/locales/models/champs/departement_champ/en.yml
  config/locales/models/champs/departement_champ/fr.yml
  config/locales/models/champs/dossier_link_champ/en.yml
  config/locales/models/champs/dossier_link_champ/fr.yml
  config/locales/models/champs/email_champ/en.yml
  config/locales/models/champs/email_champ/fr.yml
  config/locales/models/champs/epci_champ/en.yml
  config/locales/models/champs/epci_champ/fr.yml
  config/locales/models/champs/iban_champ/en.yml
  config/locales/models/champs/iban_champ/fr.yml
  config/locales/models/champs/multiple_drop_down_list/en.yml
  config/locales/models/champs/multiple_drop_down_list/fr.yml
  config/locales/models/champs/pays_champ/en.yml
  config/locales/models/champs/pays_champ/fr.yml
  config/locales/models/champs/phone_champ/en.yml
  config/locales/models/champs/phone_champ/fr.yml
  config/locales/models/champs/region_champ/en.yml
  config/locales/models/champs/region_champ/fr.yml
  config/locales/models/champs/rna_champ/en.yml
  config/locales/models/champs/rna_champ/fr.yml
  config/locales/models/champs/siret_champ/en.yml
  config/locales/models/champs/siret_champ/fr.yml
  config/locales/models/champs/titre_identite_champ/en.yml
  config/locales/models/champs/titre_identite_champ/fr.yml
  config/locales/models/service/fr.yml
  config/locales/models/siret/fr.yml
  config/locales/shared.fr.yml
  config/locales/views/contact/en.yml
  config/locales/views/contact/fr.yml
  spec/components/attachment/edit_component_spec.rb
  spec/components/attachment/multiple_component_spec.rb
  spec/controllers/champs/rna_controller_spec.rb
  spec/controllers/experts/avis_controller_spec.rb
  spec/controllers/instructeurs/dossiers_controller_spec.rb
  spec/controllers/manager/dossiers_controller_spec.rb
  spec/controllers/manager/users_controller_spec.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/controllers/users/profil_controller_spec.rb
  spec/controllers/users/transfers_controller_spec.rb
  spec/models/champs/rna_champ_spec.rb
  spec/models/champs/siret_champ_spec.rb
  spec/models/invite_spec.rb
  spec/system/users/brouillon_spec.rb
  spec/system/users/dossier_creation_spec.rb
Labels: bug, accessibilité

#11460 Tâche pour mise à jour de la date de fermeture d'une démarche
  app/tasks/maintenance/t20250314update_procedure_closed_at_task.rb
  spec/tasks/maintenance/t20250314update_procedure_closed_at_task_spec.rb
Labels: support

#11453 [Tech] Corrige des procédures sans path
  app/tasks/maintenance/t20250313_fix_missing_procedure_paths_for_discarded_procedures_task.rb
  spec/tasks/maintenance/t20250313_fix_missing_procedure_paths_for_discarded_procedures_task_spec.rb
Labels: bug

#11466 etq-admin : pas d'archive proposé pour le mois en cours
  app/controllers/administrateurs/archives_controller.rb
  spec/controllers/administrateurs/archives_controller_spec.rb
  spec/system/administrateurs/procedure_archive_and_export_spec.rb
Labels: bug

#11487 ETQ admin, pas d'erreur sur un dossier de test si le champ formatté n'a pas encore sa regex
  app/validators/expression_reguliere_validator.rb
Labels: bug

#11493 ETQ instructeur, corrige un crash du tableau lorsque la colonne "dépôt pour un tiers" est affichée
  app/components/instructeurs/cell_component.rb
  spec/components/instructeurs/cell_component_spec.rb
Labels: bug

#11494 SVA: Corrige un crash de calcul de date pour un dossier plusieurs fois mentionné incomplet, et toujours incomplet
  app/services/sva_svr_decision_date_calculator_service.rb
  spec/services/sva_svr_decision_date_calculator_service_spec.rb
Labels: bug

#11505 ETQ instructeur, pas de crash lorsque la recherche renvoie des dossiers dont l'user a été supprimé
  app/views/recherche/index.html.haml
Labels: bug

#11513 ETQ Utilisateur, correction d'un bug bloquant le depot d'un dossier ayant un champ a validation complexe dans une répétition cachée
  app/models/champs/dossier_link_champ.rb
  app/models/concerns/champ_conditional_concern.rb
  spec/models/concerns/champ_conditional_concern_spec.rb
Labels: bug, role:usager

#11478 [TECH] : etq admin je peux importer des fichiers CSV avec un BOM (indicateur d'encodage UTF-8)
  Gemfile
  Gemfile.lock
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  app/controllers/administrateurs/types_de_champ_controller.rb
  app/controllers/manager/procedures_controller.rb
  config/initializers/acsv.rb
  spec/controllers/administrateurs/types_de_champ_controller_spec.rb
  spec/fixtures/files/modele-import-referentiel-with-bom.csv
Labels: bug

#11510 ETQ Instructeur sur une démarche qui n'a pas RDV d'activé je ne veux pas voir le lien qui mène vers RDVSP
  app/views/instructeurs/procedures/_header.html.haml
Labels: bug

#11511 ETQ Instructeur je ne veux pas être bloqué lors de la prise de RDV par plusieurs instructeurs
  app/components/instructeurs/rdv_card_component.rb
  app/components/instructeurs/rdv_card_component/rdv_card_component.en.yml
  app/components/instructeurs/rdv_card_component/rdv_card_component.fr.yml
  app/components/instructeurs/rdv_card_component/rdv_card_component.html.haml
  app/controllers/instructeurs/dossiers_controller.rb
  app/controllers/instructeurs/rdvs_controller.rb
  app/models/rdv.rb
  app/views/instructeurs/dossiers/rendez_vous.html.haml
  spec/components/instructeurs/rdv_card_component_spec.rb
  spec/models/rdv_spec.rb
Labels: bug

#11521 ETQ Instructeur, je ne veux pas avoir le téléchargement de PJ qui plante aux heures de pointe
  app/lib/active_storage/downloadable_file.rb
Labels: bug
