Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2025-06, with the labels that each got.

#11707 fix(champs): type change should be properly saved
  app/models/concerns/dossier_champs_concern.rb
  spec/models/concerns/dossier_champs_concern_spec.rb
Labels: bug

#11708 ETQ Usager naviguant sur mobile, je veux que les intitulés des onglets soient visibles en intégralité
  app/views/users/dossiers/show/_header.html.haml
  config/locales/en.yml
  config/locales/fr.yml
  spec/system/users/dossier_shared_examples.rb
  spec/views/users/dossiers/show/_header.html.haml_spec.rb
Labels: design

#11720 Correctif : utilise le bon type pour le nombre de dossiers par démarche dans le manager
  app/dashboards/procedure_dashboard.rb
Labels: bug

#11729 ETQ usager je ne veux plus déposer une adresse hors BAN incomplète
  app/components/editable_champ/address_component/address_component.html.haml
  app/models/champs/address_champ.rb
  app/tasks/maintenance/t20250602fix_bad_address_data_task.rb
  app/views/dossiers/show.pdf.prawn
  config/locales/models/champs/address_champ/en.yml
  config/locales/models/champs/address_champ/fr.yml
  spec/graphql/dossier_spec.rb
  spec/models/champs/address_champ_spec.rb
  spec/system/users/brouillon_spec.rb
  spec/tasks/maintenance/t20250602fix_bad_address_data_task_spec.rb
Labels: bug

#11743 ETQ Utilisateur d'un lecteur d'écran, je veux que le bloc d'aide ne contienne pas de listes imbriquées inutiles
  app/assets/stylesheets/new_footer.scss
  app/components/procedure/service_list_contact_component.rb
  app/components/procedure/service_list_contact_component/service_list_contact_component.html.haml
  app/components/simple_format_component.rb
  app/views/shared/dossiers/_update_contact_information.html.haml
  app/views/shared/help/dropdown_items/_service_item.html.haml
Labels: accessibilité

#11768 Correctif : ETQ admin j'ai un message d'erreur approprié quand j'uploade un fichier csv sans séparateurs
  app/controllers/administrateurs/types_de_champ_controller.rb
  spec/controllers/administrateurs/types_de_champ_controller_spec.rb
  spec/fixtures/files/modele-import-referentiel-without-separators.csv
Labels: bug

#11773 ETQ usager je veux recevoir des emails avec des urls non transformées et non cassées
  app/mailers/resend_attestation_mailer.rb
  app/services/mail_template_presenter_service.rb
  spec/models/dossier_spec.rb
Labels: bug
