Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2025-02, with the labels that each got.

#11286 ETQ admin: empêche de récupérer l'unique et dernier lien pointant sur une autre de ses démarches
  app/models/concerns/procedure_path_concern.rb
  config/locales/en.yml
  config/locales/fr.yml
  spec/models/concerns/procedure_path_concern_spec.rb
Labels: bug

#11277 ETQ Usager naviguant au clavier sur mobile, je veux que la prise de focus soit toujours visible
  app/assets/stylesheets/forms.scss
  app/assets/stylesheets/layouts.scss
Labels: bug, accessibilité

#11307 Tech: fix formattage de column date stringifiée issue d'un jsonpath
  app/components/instructeurs/cell_component.rb
  spec/components/instructeurs/cell_component_spec.rb
Labels: bug

#11295 Correctifs dans la vue Gestion des instructeurs etq instructeur
  app/components/procedure/import_component/import_component.html.haml
  app/components/procedure/instructeurs_management_component/instructeurs_management_component.html.haml
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  app/controllers/instructeurs/groupe_instructeurs_controller.rb
  app/models/dossier.rb
  app/tasks/maintenance/t20250206destroy_contact_informations_in_not_routed_procedures_task.rb
  app/views/administrateurs/groupe_instructeurs/show.html.haml
  app/views/instructeurs/groupe_instructeurs/show.html.haml
  app/views/shared/groupe_instructeurs/_contact_information.html.haml
  app/views/shared/groupe_instructeurs/_instructeurs.html.haml
  config/locales/views/administrateurs/groupe_instructeurs/en.yml
  config/locales/views/administrateurs/groupe_instructeurs/fr.yml
  config/locales/views/shared/en.yml
  config/locales/views/shared/fr.yml
  spec/tasks/maintenance/t20250206destroy_contact_informations_in_not_routed_procedures_task_spec.rb
Labels: bug

#11334 ETQ Instructeur, corrige l'acces de la page de contact d'un groupe
  app/views/shared/groupe_instructeurs/_contact_information.html.haml
  spec/controllers/instructeurs/groupe_instructeurs_controller_spec.rb
Labels: bug, role:instructeur

#11324 ETQ Utilisateur d'un lecteur d'écran, je veux que les boutons de suppression d'un bloc répétables aient des intitulés différents
  app/components/editable_champ/repetition_row_component/repetition_row_component.en.yml
  app/components/editable_champ/repetition_row_component/repetition_row_component.fr.yml
  app/components/editable_champ/repetition_row_component/repetition_row_component.html.haml
Labels: bug, accessibilité

#11346 ETQ Instructeur, je peux filtrer sur les colonnes de csv mm si elles comportent un nil
  app/models/types_de_champ/drop_down_list_type_de_champ.rb
  spec/factories/referentiel.rb
  spec/models/types_de_champ/drop_down_list_type_de_champ_spec.rb
Labels: bug, role:instructeur

#11347 fix(js): check if AbortSignal.any is implemented
  app/javascript/shared/utils.ts
Labels: bug

#11367 ETQ admin: l'attestation utilise les valeurs issues du champ référentiel
  app/models/types_de_champ/drop_down_list_type_de_champ.rb
  spec/models/concerns/tags_substitution_concern_spec.rb
Labels: bug

#11357 ETQ usager, je veux que l'exemple du champ RNF ne soit pas indiqué comme un format
  config/locales/models/champs/rnf_champ/en.yml
  config/locales/models/champs/rnf_champ/fr.yml
Labels: accessibilité

#11351 ETQ Adminsitrateur, je peux cloner une démarche avec une drop_down_list utilisant un référentiel
  spec/factories/procedure.rb
  spec/models/procedure_spec.rb
Labels: bug, role:admin

#11379 fix(fetch): 0 code is invalid, browsers will crash
  app/javascript/shared/utils.ts
Labels: bug
