Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2025-04, with the labels that each got.

#11534 ETQ usager, corrige l'affichage de la première ligne de répétition lorsque l'ensemble du bloc est conditionné
  app/controllers/concerns/turbo_champs_concern.rb
  spec/controllers/users/dossiers_controller_spec.rb
  spec/system/users/brouillon_spec.rb
Labels: bug

#11535 ETQ instructeur, fix notification et affichage de la galerie lorsque la dernière PJ a été retirée
  app/views/instructeurs/dossiers/_header_bottom.html.haml
  app/views/instructeurs/dossiers/pieces_jointes.html.haml
Labels: bug

#11563 Correctif : ETQ instructeur membre d'un groupe instructeur je peux personnaliser les infos de contact
  app/views/shared/groupe_instructeurs/_contact_information.html.haml
Labels: bug

#11518 ETQ Opérateur, j'ai davantage de log lors de la suppression de dossier en brouillon ou sur des procédures en test
  app/models/dossier.rb
  spec/models/dossier_spec.rb
Labels: ops

#11574 ETQ Admin, je veux pouvoir me connecter à RDV
  config/initializers/omniauth.rb
Labels: bug

#11583 ETQ Usager, je veux que l'exemple d'IBAN soit correct et que le contenu ne déborde pas sur les terminaux de faible largeur
  app/assets/stylesheets/forms.scss
  config/locales/models/champs/iban_champ/fr.yml
  spec/system/users/brouillon_spec.rb
Labels: bug, accessibilité

#11571 Correctif : ETQ admin je peux importer un fichier csv au format iso 8859
  app/controllers/administrateurs/groupe_instructeurs_controller.rb
  app/controllers/administrateurs/types_de_champ_controller.rb
  app/controllers/manager/procedures_controller.rb
  spec/controllers/administrateurs/groupe_instructeurs_controller_spec.rb
  spec/fixtures/files/groupe_iso_8859.csv
  spec/fixtures/files/groupe_iso_8859_invalid_characters.csv
Labels: bug

#11587 fix(active_storage): remove files from object storage only if no attachements left
  app/jobs/delayed_purge_job.rb
  spec/jobs/delayed_purge_job_spec.rb
Labels: bug

#11607 fix(champ): cast from text to formatted and vice versa
  app/models/columns/champ_column.rb
  app/models/type_de_champ.rb
  spec/models/columns/champ_column_spec.rb
  spec/models/type_de_champ_spec.rb
Labels: bug

#11617 ETQ Expert, je veux que la page de création de compte soit plus accessible
  app/components/instructeurs/activate_account_form_component/activate_account_form_component.html.haml
  app/views/experts/avis/sign_up.html.haml
  config/locales/en.yml
  config/locales/fr.yml
Labels: accessibilité

#11589 ETQ Usager d'un lecteur d'écran, je veux que je le message d'échec d'une création de compte ou du changement de mot de passe me soit restitué
  app/views/devise/passwords/edit.html.haml
  app/views/users/registrations/new.html.haml
Labels: accessibilité

#11630 ETQ Usager utilisant un lecteur d'écran, j'aimerai que les listes n'aient pas d'items vides
  app/components/procedure/service_list_contact_component/service_list_contact_component.html.haml
Labels: accessibilité

#11629 ETQ Instructeur utilisant un lecteur d'écran, en arrivant depuis un lien externe sur la page de création de compte, je ne veux pas d'autofocus forcé
  app/components/instructeurs/activate_account_form_component/activate_account_form_component.en.yml
  app/components/instructeurs/activate_account_form_component/activate_account_form_component.fr.yml
  app/components/instructeurs/activate_account_form_component/activate_account_form_component.html.haml
  spec/system/instructeurs/instructeur_creation_spec.rb
  spec/system/routing/rules_full_scenario_spec.rb
Labels: accessibilité
