Repository demarches-simplifiees/demarches-simplifiees.fr, pull requests merged in 2025-01, with the labels that each got.

#11200 ETQ usager, avec un mandat sans notification, je peux modifier mon identité
  app/components/dossiers/individual_form_component/individual_form_component.html.haml
Labels: bug, role:usager

#11197 Suppression du 2fa Agent Connect, en attente de l'implementation alternative chez Pro Connect
  app/assets/images/instructions_moncomptepro.png
  app/controllers/agent_connect/agent_controller.rb
  app/controllers/users/sessions_controller.rb
  app/services/agent_connect_service.rb
  app/views/agent_connect/agent/explanation_2fa.html.haml
  app/views/agent_connect/agent/relogin_after_2fa_config.html.haml
  config/env.example.optional
  config/routes.rb
  spec/controllers/agent_connect/agent_controller_spec.rb
  spec/controllers/users/sessions_controller_spec.rb
  spec/services/agent_connect_service_spec.rb
Labels: role:instructeur

#11194 ETQ instructeur: la page de la liste des démarche va plus vite s'il y a des milliers de dossiers
  db/migrate/20250107155455_add_index_to_dossiers_on_groupe_instructeur_id_and_state.rb
  db/schema.rb
Labels: role:instructeur, performances

#11183 Tech: supprime les mécanismes de rotation de clés du passage à rails 7.0
  app/services/encryption_service.rb
  app/tasks/maintenance/rotate_api_particulier_token_encryption_task.rb
  config/initializers/cookie_rotator.rb
  spec/services/encryption_service_spec.rb
  spec/tasks/maintenance/rotate_api_particulier_token_encryption_task_spec.rb
Labels: a-communiquer-instances

#11234 perf: accélère la sauvegarde des champs conditionnés en cachant les calculs de visibilité
  app/models/concerns/dossier_champs_concern.rb
  spec/models/concerns/champ_validate_concern_spec.rb
Labels: bug, role:usager, performances

#11240 Tech: rétabli la liste des instructeurs ajoutés en copie cachée
  app/mailers/groupe_instructeur_mailer.rb
  spec/mailers/groupe_instructeur_mailer_spec.rb
Labels: bug

#11256 Correction d'un bug d'affichage sur les PDF
  Gemfile
  Gemfile.lock
  app/views/administrateurs/attestation_templates/show.pdf.prawn
  app/views/dossiers/dossier_vide.pdf.prawn
  app/views/dossiers/show.pdf.prawn
  app/views/users/dossiers/papertrail.pdf.prawn
Labels: bug

#11270 ETQ usager, le PDF vide de la démarche ne contient le champ date de naissance que si nécessaire
  app/views/dossiers/dossier_vide.pdf.prawn
Labels: bug

#11269 ETQ instructeur, corrrige le tri par "code naf" des dossiers
  app/services/dossier_filter_service.rb
  spec/services/dossier_filter_service_spec.rb
Labels: bug

#11272 fix(attachement): if champ attachement is already destroyed don’t crash
  app/controllers/attachments_controller.rb
Labels: bug

#11274 ETQ admin, le compteur de dossiers à archiver correspond aux dossiers réellement téléchargés
  app/controllers/administrateurs/archives_controller.rb
  spec/controllers/administrateurs/archives_controller_spec.rb
Labels: bug
